/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hr.skrbina.edunovazavrsnigalerija.view;

import hr.skrbina.edunovazavrsnigalerija.controller.ObradaAutor;
import hr.skrbina.edunovazavrsnigalerija.model.Autor;
import hr.skrbina.edunovazavrsnigalerija.utility.Iban;
import hr.skrbina.edunovazavrsnigalerija.utility.Oib;
import hr.skrbina.edunovazavrsnigalerija.utility.SkrbinaException;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.DefaultListSelectionModel;
import javax.swing.Timer;

/**
 *
 * @author Hrvoje
 */
public class Autori extends javax.swing.JFrame {

    private final ObradaAutor obrada;
    private Autor entitet;
    
    /* Creates new form Autori */
    public Autori() {
        initComponents();
        obrada = new ObradaAutor();
        setTitle(Aplikacija.NASLOV_APP + " - Autori");
        defaultStart();
        autoriLst.setCellRenderer(new OsobaCellRenderer());
        autoriLst.setSelectionMode(DefaultListSelectionModel.SINGLE_SELECTION); 
        traziTxt.requestFocus();
        SimpleDateFormat myTime = new SimpleDateFormat("HH:mm:ss" + "    " + "dd.MM.YYYY.");
        Timer SimpleTimer = new Timer(1000, (ActionEvent e) -> {
            vrijemeLbl.setText(myTime.format(new Date()));
        });
        SimpleTimer.start(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ocistiBttn = new javax.swing.JButton();
        imeTxt = new javax.swing.JTextField();
        generirajIBAN = new javax.swing.JButton();
        obrisiBttn = new javax.swing.JButton();
        datumTxt = new javax.swing.JTextField();
        prezime = new javax.swing.JLabel();
        iban = new javax.swing.JLabel();
        kontaktTxt = new javax.swing.JTextField();
        generirajOib = new javax.swing.JButton();
        traziTxt = new javax.swing.JTextField();
        kontakt = new javax.swing.JLabel();
        mjesto = new javax.swing.JLabel();
        izmijeniBttn = new javax.swing.JButton();
        ibanTxt = new javax.swing.JTextField();
        ime = new javax.swing.JLabel();
        mrTxt = new javax.swing.JTextField();
        povratakBttn = new javax.swing.JButton();
        oib = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        autoriLst = new javax.swing.JList<>();
        prezimeTxt = new javax.swing.JTextField();
        traziBttn = new javax.swing.JButton();
        datum = new javax.swing.JLabel();
        dodajBttn = new javax.swing.JButton();
        oibTxt = new javax.swing.JTextField();
        porukaLbl = new javax.swing.JLabel();
        brojDJ = new javax.swing.JLabel();
        brojDjelaTxt = new javax.swing.JTextField();
        vrijemeLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(691, 322));
        setMinimumSize(new java.awt.Dimension(691, 322));
        setName(""); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(691, 322));

        ocistiBttn.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        ocistiBttn.setText("Očisti");
        ocistiBttn.setMaximumSize(new java.awt.Dimension(116, 32));
        ocistiBttn.setMinimumSize(new java.awt.Dimension(116, 32));
        ocistiBttn.setPreferredSize(new java.awt.Dimension(116, 32));
        ocistiBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ocistiBttnActionPerformed(evt);
            }
        });

        imeTxt.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        imeTxt.setText("ime");
        imeTxt.setMaximumSize(new java.awt.Dimension(368, 30));
        imeTxt.setMinimumSize(new java.awt.Dimension(368, 30));
        imeTxt.setName(""); // NOI18N
        imeTxt.setPreferredSize(new java.awt.Dimension(368, 30));

        generirajIBAN.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        generirajIBAN.setText("Generiraj IBAN");
        generirajIBAN.setMaximumSize(new java.awt.Dimension(195, 30));
        generirajIBAN.setMinimumSize(new java.awt.Dimension(195, 30));
        generirajIBAN.setPreferredSize(new java.awt.Dimension(195, 30));
        generirajIBAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generirajIBANActionPerformed(evt);
            }
        });

        obrisiBttn.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        obrisiBttn.setText("Obriši");
        obrisiBttn.setMaximumSize(new java.awt.Dimension(78, 32));
        obrisiBttn.setMinimumSize(new java.awt.Dimension(78, 32));
        obrisiBttn.setPreferredSize(new java.awt.Dimension(78, 32));
        obrisiBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obrisiBttnActionPerformed(evt);
            }
        });

        datumTxt.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        datumTxt.setText("datum");
        datumTxt.setMaximumSize(new java.awt.Dimension(368, 30));
        datumTxt.setMinimumSize(new java.awt.Dimension(368, 30));
        datumTxt.setName(""); // NOI18N
        datumTxt.setPreferredSize(new java.awt.Dimension(368, 30));

        prezime.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        prezime.setText("Prezime:");

        iban.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        iban.setText("IBAN:");

        kontaktTxt.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        kontaktTxt.setText("kontakt");
        kontaktTxt.setMaximumSize(new java.awt.Dimension(368, 30));
        kontaktTxt.setMinimumSize(new java.awt.Dimension(368, 30));
        kontaktTxt.setName(""); // NOI18N
        kontaktTxt.setPreferredSize(new java.awt.Dimension(368, 30));

        generirajOib.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        generirajOib.setText("Generiraj OIB");
        generirajOib.setMaximumSize(new java.awt.Dimension(195, 30));
        generirajOib.setMinimumSize(new java.awt.Dimension(195, 30));
        generirajOib.setPreferredSize(new java.awt.Dimension(195, 30));
        generirajOib.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generirajOibActionPerformed(evt);
            }
        });

        traziTxt.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        traziTxt.setText("trazi");
        traziTxt.setMaximumSize(new java.awt.Dimension(220, 30));
        traziTxt.setMinimumSize(new java.awt.Dimension(220, 30));
        traziTxt.setPreferredSize(new java.awt.Dimension(220, 30));
        traziTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                traziTxtKeyReleased(evt);
            }
        });

        kontakt.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        kontakt.setText("Kontakt:");

        mjesto.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        mjesto.setText("Mjesto rođenja:");

        izmijeniBttn.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        izmijeniBttn.setText("Izmijeni");
        izmijeniBttn.setMaximumSize(new java.awt.Dimension(78, 32));
        izmijeniBttn.setMinimumSize(new java.awt.Dimension(78, 32));
        izmijeniBttn.setPreferredSize(new java.awt.Dimension(78, 32));
        izmijeniBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                izmijeniBttnActionPerformed(evt);
            }
        });

        ibanTxt.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        ibanTxt.setText("iban");
        ibanTxt.setMaximumSize(new java.awt.Dimension(167, 30));
        ibanTxt.setMinimumSize(new java.awt.Dimension(167, 30));
        ibanTxt.setName(""); // NOI18N
        ibanTxt.setPreferredSize(new java.awt.Dimension(167, 30));

        ime.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        ime.setText("Ime:");

        mrTxt.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        mrTxt.setText("mjesto");
        mrTxt.setMaximumSize(new java.awt.Dimension(368, 30));
        mrTxt.setMinimumSize(new java.awt.Dimension(368, 30));
        mrTxt.setName(""); // NOI18N
        mrTxt.setPreferredSize(new java.awt.Dimension(368, 30));

        povratakBttn.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        povratakBttn.setText("Povratak");
        povratakBttn.setMaximumSize(new java.awt.Dimension(98, 32));
        povratakBttn.setMinimumSize(new java.awt.Dimension(98, 32));
        povratakBttn.setPreferredSize(new java.awt.Dimension(98, 32));
        povratakBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                povratakBttnActionPerformed(evt);
            }
        });

        oib.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        oib.setText("OIB:");

        jScrollPane1.setMaximumSize(new java.awt.Dimension(296, 265));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(296, 252));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(296, 252));

        autoriLst.setFont(new java.awt.Font("Georgia", 2, 14)); // NOI18N
        autoriLst.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                autoriLstValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(autoriLst);

        prezimeTxt.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        prezimeTxt.setText("prezime");
        prezimeTxt.setMaximumSize(new java.awt.Dimension(368, 30));
        prezimeTxt.setMinimumSize(new java.awt.Dimension(368, 30));
        prezimeTxt.setName(""); // NOI18N
        prezimeTxt.setPreferredSize(new java.awt.Dimension(368, 30));

        traziBttn.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        traziBttn.setText("Traži");
        traziBttn.setMaximumSize(new java.awt.Dimension(78, 30));
        traziBttn.setMinimumSize(new java.awt.Dimension(78, 30));
        traziBttn.setPreferredSize(new java.awt.Dimension(78, 30));
        traziBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                traziBttnActionPerformed(evt);
            }
        });

        datum.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        datum.setText("Datum rođenja:");

        dodajBttn.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        dodajBttn.setText("Dodaj");
        dodajBttn.setMaximumSize(new java.awt.Dimension(78, 32));
        dodajBttn.setMinimumSize(new java.awt.Dimension(78, 32));
        dodajBttn.setPreferredSize(new java.awt.Dimension(78, 32));
        dodajBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dodajBttnActionPerformed(evt);
            }
        });

        oibTxt.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        oibTxt.setText("oib");
        oibTxt.setMaximumSize(new java.awt.Dimension(167, 30));
        oibTxt.setMinimumSize(new java.awt.Dimension(167, 30));
        oibTxt.setName(""); // NOI18N
        oibTxt.setPreferredSize(new java.awt.Dimension(167, 30));

        porukaLbl.setFont(new java.awt.Font("Georgia", 2, 14)); // NOI18N
        porukaLbl.setText("jLabel9");

        brojDJ.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        brojDJ.setText("Broj djela:");

        brojDjelaTxt.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        brojDjelaTxt.setText("djela");
        brojDjelaTxt.setMaximumSize(new java.awt.Dimension(368, 30));
        brojDjelaTxt.setMinimumSize(new java.awt.Dimension(368, 30));
        brojDjelaTxt.setPreferredSize(new java.awt.Dimension(368, 30));

        vrijemeLbl.setFont(new java.awt.Font("Georgia", 2, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(traziTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(traziBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(vrijemeLbl)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(iban)
                                .addComponent(mjesto)
                                .addComponent(oib)
                                .addComponent(datum)
                                .addComponent(prezime)
                                .addComponent(ime)
                                .addComponent(kontakt)
                                .addComponent(brojDJ))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(mrTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(17, 17, 17)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(ibanTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(generirajIBAN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(imeTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(prezimeTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(datumTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(oibTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(generirajOib, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(kontaktTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(brojDjelaTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(dodajBttn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(izmijeniBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(obrisiBttn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(ocistiBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(povratakBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(1, 1, 1)))
                    .addComponent(porukaLbl))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(imeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ime))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(traziBttn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(traziTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(prezimeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(prezime))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(datumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(datum))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(oib)
                                .addComponent(generirajOib, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(oibTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mrTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mjesto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ibanTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iban)
                            .addComponent(generirajIBAN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kontaktTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kontakt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(brojDjelaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(brojDJ))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(povratakBttn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(obrisiBttn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ocistiBttn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(izmijeniBttn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dodajBttn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(porukaLbl)
                    .addComponent(vrijemeLbl))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void traziTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_traziTxtKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            ucitajPodatke();
        }
    }//GEN-LAST:event_traziTxtKeyReleased

    private void traziBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_traziBttnActionPerformed
        ucitajZaTrazi();
    }//GEN-LAST:event_traziBttnActionPerformed

    private void autoriLstValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_autoriLstValueChanged
        entitet = autoriLst.getSelectedValue();
        if (entitet == null) {
            return;
        }

        if (!autoriLst.isSelectionEmpty()) {
            obrisiBttn.setEnabled(true);
            izmijeniBttn.setEnabled(true);
        }

        if (evt.getValueIsAdjusting()) {
            return;
        }
        
        imeTxt.setText(entitet.getIme());
        prezimeTxt.setText(entitet.getPrezime());
        datumTxt.setText(entitet.getRodjendan());
        oibTxt.setText(entitet.getOib());
        mrTxt.setText(entitet.getMjesto_Rodjenja());
        ibanTxt.setText(entitet.getIBAN());
        kontaktTxt.setText(entitet.getKontakt());
        if(entitet.getDjela().isEmpty()) {
            brojDjelaTxt.setText("0");
        }
        else {
            brojDjelaTxt.setText("" + entitet.getDjela().size());
        }
    }//GEN-LAST:event_autoriLstValueChanged

    private void generirajIBANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generirajIBANActionPerformed
        ibanTxt.setText(Iban.getIbanIiCentrala());
    }//GEN-LAST:event_generirajIBANActionPerformed

    private void generirajOibActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generirajOibActionPerformed
        oibTxt.setText(Oib.getOibIiCentrala());
    }//GEN-LAST:event_generirajOibActionPerformed

    private void ocistiBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ocistiBttnActionPerformed
        defaultStart();
    }//GEN-LAST:event_ocistiBttnActionPerformed

    private void obrisiBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obrisiBttnActionPerformed
        entitet = autoriLst.getSelectedValue();
        if (entitet == null) {
            return;
        }

        obrada.setEntitet(entitet);

        try {
            obrada.delete();
            ucitajPodatke();
            defaultStart();
        } catch (SkrbinaException e) {
            porukaLbl.setText(e.getPoruka());
        }
    }//GEN-LAST:event_obrisiBttnActionPerformed

    private void izmijeniBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_izmijeniBttnActionPerformed
        entitet = autoriLst.getSelectedValue();
        if (entitet == null) {
            return;
        }
        postaviVrijednostiUEntitet();

        try {
            obrada.update();
            ucitajPodatke();
            defaultStart();
        } catch (SkrbinaException e) {
            porukaLbl.setText(e.getPoruka());
        }
    }//GEN-LAST:event_izmijeniBttnActionPerformed

    private void povratakBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_povratakBttnActionPerformed
        this.dispose();
    }//GEN-LAST:event_povratakBttnActionPerformed

    private void dodajBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dodajBttnActionPerformed
        porukaLbl.setText("");
        entitet = new Autor();

        postaviVrijednostiUEntitet();

        obrada.setEntitet(entitet);
        try {
            obrada.create();
            ucitajPodatke();
            defaultStart();
        } catch (SkrbinaException ex) {
            porukaLbl.setText(ex.getPoruka());
        }
    }//GEN-LAST:event_dodajBttnActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
 /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Autori().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<Autor> autoriLst;
    private javax.swing.JLabel brojDJ;
    private javax.swing.JTextField brojDjelaTxt;
    private javax.swing.JLabel datum;
    private javax.swing.JTextField datumTxt;
    private javax.swing.JButton dodajBttn;
    private javax.swing.JButton generirajIBAN;
    private javax.swing.JButton generirajOib;
    private javax.swing.JLabel iban;
    private javax.swing.JTextField ibanTxt;
    private javax.swing.JLabel ime;
    private javax.swing.JTextField imeTxt;
    private javax.swing.JButton izmijeniBttn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel kontakt;
    private javax.swing.JTextField kontaktTxt;
    private javax.swing.JLabel mjesto;
    private javax.swing.JTextField mrTxt;
    private javax.swing.JButton obrisiBttn;
    private javax.swing.JButton ocistiBttn;
    private javax.swing.JLabel oib;
    private javax.swing.JTextField oibTxt;
    private javax.swing.JLabel porukaLbl;
    private javax.swing.JButton povratakBttn;
    private javax.swing.JLabel prezime;
    private javax.swing.JTextField prezimeTxt;
    private javax.swing.JButton traziBttn;
    private javax.swing.JTextField traziTxt;
    private javax.swing.JLabel vrijemeLbl;
    // End of variables declaration//GEN-END:variables

    private void defaultStart() {
        ucitajPodatke();
        traziTxt.setText("");
        imeTxt.setText("");
        prezimeTxt.setText("");
        datumTxt.setText("");
        oibTxt.setText("");
        mrTxt.setText("");
        ibanTxt.setText("");
        kontaktTxt.setText("");
        porukaLbl.setText("");
        brojDjelaTxt.setText("");
        autoriLst.clearSelection();
        if (autoriLst.isSelectionEmpty()) {
            izmijeniBttn.setEnabled(false);
            obrisiBttn.setEnabled(false);
        }
    }

    private void ucitajPodatke() {
        DefaultListModel<Autor> m = new DefaultListModel<>();
        obrada.getPodaci().forEach(r -> m.addElement(r));
        autoriLst.setModel(m);
    }

    private void ucitajZaTrazi() {
        DefaultListModel<Autor> m = new DefaultListModel<>();
        obrada.getPodaci(traziTxt.getText()).forEach(k -> m.addElement(k));
        autoriLst.setModel(m);
    }

    private void postaviVrijednostiUEntitet() {
        entitet.setIme(imeTxt.getText());
        entitet.setPrezime(prezimeTxt.getText());
        entitet.setRodjendan(datumTxt.getText());
        entitet.setOib(oibTxt.getText());
        entitet.setMjesto_Rodjenja(mrTxt.getText());
        entitet.setIBAN(ibanTxt.getText());
        entitet.setKontakt(kontaktTxt.getText());
        obrada.setEntitet(entitet);
    }
}
