/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hr.skrbina.edunovazavrsnigalerija.view;

import hr.skrbina.edunovazavrsnigalerija.controller.ObradaOperater;
import hr.skrbina.edunovazavrsnigalerija.model.Operater;
import java.awt.event.KeyEvent;
import javax.mail.internet.AddressException;
import javax.mail.internet.InternetAddress;
import javax.swing.JOptionPane;

/**
 *
 * @author Hrvoje
 */
public class Autorizacija extends javax.swing.JFrame {

    /**
     * Creates new form Autorizacija
     */
    public Autorizacija() {
        initComponents();
        setTitle("Gallery Exclusive - Autorizacija");
        emailTxt.requestFocus();
        emailTxt.setText("hskrbina@egallery.hr");
        pswTxt.setText("t");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imgLbl = new javax.swing.JLabel();
        textLbl = new javax.swing.JLabel();
        pswTxt = new javax.swing.JPasswordField();
        emailTxt = new javax.swing.JTextField();
        prijavaBttn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 550, 500));
        setFocusable(false);
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 550, 500));
        setMaximumSize(new java.awt.Dimension(550, 500));
        setMinimumSize(new java.awt.Dimension(525, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(550, 500));

        imgLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login_art.png"))); // NOI18N
        imgLbl.setText("jLabel2");

        textLbl.setFont(new java.awt.Font("Georgia", 1, 22)); // NOI18N
        textLbl.setText("DOBRODOŠLI U \"EXCLUSIVE\" GALERIJU");

        pswTxt.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        pswTxt.setText("Lozinka");
        pswTxt.setToolTipText("Unesite korisničku lozinku.");
        pswTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pswTxtKeyReleased(evt);
            }
        });

        emailTxt.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        emailTxt.setText("EMail");
        emailTxt.setToolTipText("Unesite korisnički e-mail.");
        emailTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                emailTxtKeyReleased(evt);
            }
        });

        prijavaBttn.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        prijavaBttn.setText("Ulogiraj se");
        prijavaBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prijavaBttnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(imgLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textLbl)
                    .addComponent(pswTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prijavaBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(imgLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(emailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pswTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(prijavaBttn, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void prijavaBttnActionPerformed(java.awt.event.ActionEvent evt) {
        prijaviSe();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Autorizacija.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Autorizacija.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Autorizacija.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Autorizacija.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Autorizacija().setVisible(true);
        });
    }
    private void emailTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailTxtKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER && !emailTxt.getText().trim().isEmpty()) {
            pswTxt.requestFocus();
        }
    }//GEN-LAST:event_emailTxtKeyReleased


    private void pswTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pswTxtKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER && pswTxt.getPassword().length > 0) {
            prijaviSe();
        }
    }//GEN-LAST:event_pswTxtKeyReleased

    private void btnPrijava(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrijavaActionPerformed
        prijaviSe();
    }//GEN-LAST:event_btnPrijavaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField emailTxt;
    private javax.swing.JLabel imgLbl;
    private javax.swing.JButton prijavaBttn;
    private javax.swing.JPasswordField pswTxt;
    private javax.swing.JLabel textLbl;
    // End of variables declaration//GEN-END:variables

    private void prijaviSe() {
        if (emailTxt.getText().trim().isEmpty()) {
            emailTxt.requestFocus();
            JOptionPane.showMessageDialog(rootPane, "EMail je obavezan!");
            return;
        }

        try {
            InternetAddress emailAddr = new InternetAddress(emailTxt.getText());
            emailAddr.validate();
        } catch (AddressException ex) {
            emailTxt.requestFocus();
            JOptionPane.showMessageDialog(rootPane, "EMail nije valjan!");
            return;
        }

        if (pswTxt.getPassword().length == 0) {
            pswTxt.requestFocus();
            JOptionPane.showMessageDialog(rootPane, "Lozinka je obavezna!");
            return;
        }

        ObradaOperater obop = new ObradaOperater();
        Operater operater = obop.autoriziraj(emailTxt.getText(), pswTxt.getPassword());
        if (operater == null) {
            JOptionPane.showMessageDialog(rootPane, "Nesipravna kombinacija EMaila i lozinke!");
            return;
        }

        Aplikacija.operater = operater;

        Izbornik izb = new Izbornik();
        izb.setVisible(true);
        izb.setLocationRelativeTo(null);
        dispose();
    }
}