/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hr.skrbina.edunovazavrsnigalerija.view;

import hr.skrbina.edunovazavrsnigalerija.controller.ObradaAutor;
import hr.skrbina.edunovazavrsnigalerija.controller.ObradaDjelo;
import hr.skrbina.edunovazavrsnigalerija.model.Autor;
import hr.skrbina.edunovazavrsnigalerija.model.Djelo;
import hr.skrbina.edunovazavrsnigalerija.utility.SkrbinaException;
import java.awt.event.ActionEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListSelectionModel;
import javax.swing.ImageIcon;
import javax.swing.DefaultListModel;
import javax.swing.Timer;

/**
 *
 * @author Hrvoje
 */
public class Djela extends javax.swing.JFrame {

    private final ObradaDjelo obrada;
    private Djelo entitet;
    private ImageIcon img;
    private final ImageIcon dfltImg = new ImageIcon(getClass().getResource("/default.jpg"));

    /**
     * Creates new form Djela
     */
    public Djela() {
        initComponents();
        obrada = new ObradaDjelo();
        setTitle(Aplikacija.NASLOV_APP + " - Djela");
        ucitajPodatke();
        djelaLst.setCellRenderer(new DjeloCellRenderer());
        checkAndEmpty();
        SimpleDateFormat myTime = new SimpleDateFormat("HH:mm:ss" + "    " + "dd.MM.YYYY.");
        Timer SimpleTimer = new Timer(1000, (ActionEvent e) -> {
            vrijemeLbl.setText(myTime.format(new Date()));
        });
        SimpleTimer.start(); 
        cijena.setToolTipText("Procijenjena cijena u €.");
        opisTxt.setWrapStyleWord(true);
        opisTxt.setLineWrap(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pregledLbl = new javax.swing.JLabel();
        naziv = new javax.swing.JLabel();
        autor = new javax.swing.JLabel();
        datum = new javax.swing.JLabel();
        nazivTxt = new javax.swing.JTextField();
        opis = new javax.swing.JLabel();
        dodajBttn = new javax.swing.JButton();
        izmijeniBttn = new javax.swing.JButton();
        obrisiBttn = new javax.swing.JButton();
        povratakBttn = new javax.swing.JButton();
        autorCmb = new javax.swing.JComboBox<>();
        porukaLbl = new javax.swing.JLabel();
        cijenaTxt = new javax.swing.JTextField();
        cijena = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        opisTxt = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        datumTxt = new javax.swing.JTextField();
        vrijemeLbl = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        djelaLst = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pregledLbl.setMaximumSize(new java.awt.Dimension(536, 300));
        pregledLbl.setMinimumSize(new java.awt.Dimension(536, 300));
        pregledLbl.setName(""); // NOI18N
        pregledLbl.setPreferredSize(new java.awt.Dimension(536, 300));

        naziv.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        naziv.setText("Naziv:");

        autor.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        autor.setText("Autor:");

        datum.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        datum.setText("Datum:");

        nazivTxt.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        nazivTxt.setMaximumSize(new java.awt.Dimension(578, 30));
        nazivTxt.setMinimumSize(new java.awt.Dimension(578, 30));
        nazivTxt.setPreferredSize(new java.awt.Dimension(578, 30));

        opis.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        opis.setText("Opis:");

        dodajBttn.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        dodajBttn.setText("Dodaj");
        dodajBttn.setMaximumSize(new java.awt.Dimension(96, 38));
        dodajBttn.setMinimumSize(new java.awt.Dimension(96, 38));
        dodajBttn.setPreferredSize(new java.awt.Dimension(96, 38));
        dodajBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dodajBttnActionPerformed(evt);
            }
        });

        izmijeniBttn.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        izmijeniBttn.setText("Izmijeni");
        izmijeniBttn.setMaximumSize(new java.awt.Dimension(96, 38));
        izmijeniBttn.setMinimumSize(new java.awt.Dimension(96, 38));
        izmijeniBttn.setPreferredSize(new java.awt.Dimension(96, 38));
        izmijeniBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                izmijeniBttnActionPerformed(evt);
            }
        });

        obrisiBttn.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        obrisiBttn.setText("Obriši");
        obrisiBttn.setMaximumSize(new java.awt.Dimension(96, 38));
        obrisiBttn.setMinimumSize(new java.awt.Dimension(96, 38));
        obrisiBttn.setPreferredSize(new java.awt.Dimension(96, 38));
        obrisiBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obrisiBttnActionPerformed(evt);
            }
        });

        povratakBttn.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        povratakBttn.setText("Povratak");
        povratakBttn.setMaximumSize(new java.awt.Dimension(96, 38));
        povratakBttn.setMinimumSize(new java.awt.Dimension(96, 38));
        povratakBttn.setPreferredSize(new java.awt.Dimension(96, 38));
        povratakBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                povratakBttnActionPerformed(evt);
            }
        });

        autorCmb.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        autorCmb.setMaximumSize(new java.awt.Dimension(578, 30));
        autorCmb.setMinimumSize(new java.awt.Dimension(578, 30));
        autorCmb.setPreferredSize(new java.awt.Dimension(578, 30));

        porukaLbl.setFont(new java.awt.Font("Georgia", 2, 14)); // NOI18N
        porukaLbl.setText("jLabel1");

        cijenaTxt.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        cijenaTxt.setMaximumSize(new java.awt.Dimension(578, 30));
        cijenaTxt.setMinimumSize(new java.awt.Dimension(578, 30));
        cijenaTxt.setPreferredSize(new java.awt.Dimension(578, 30));

        cijena.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        cijena.setText("Cijena:");

        opisTxt.setColumns(20);
        opisTxt.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        opisTxt.setLineWrap(true);
        opisTxt.setRows(5);
        jScrollPane2.setViewportView(opisTxt);

        jButton1.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jButton1.setText("Očisti");
        jButton1.setMaximumSize(new java.awt.Dimension(96, 38));
        jButton1.setMinimumSize(new java.awt.Dimension(96, 38));
        jButton1.setPreferredSize(new java.awt.Dimension(96, 38));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        datumTxt.setMaximumSize(new java.awt.Dimension(578, 30));
        datumTxt.setMinimumSize(new java.awt.Dimension(578, 30));
        datumTxt.setPreferredSize(new java.awt.Dimension(578, 30));

        vrijemeLbl.setFont(new java.awt.Font("Georgia", 2, 14)); // NOI18N
        vrijemeLbl.setText("jLabel1");

        djelaLst.setFont(new java.awt.Font("Georgia", 2, 14)); // NOI18N
        djelaLst.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        djelaLst.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                djelaLstValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(djelaLst);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(naziv)
                            .addComponent(autor)
                            .addComponent(datum)
                            .addComponent(opis)
                            .addComponent(cijena))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
                            .addComponent(nazivTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(autorCmb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(datumTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cijenaTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dodajBttn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(izmijeniBttn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(povratakBttn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(obrisiBttn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pregledLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(vrijemeLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(porukaLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pregledLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dodajBttn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(izmijeniBttn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(obrisiBttn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(opis)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(povratakBttn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cijenaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cijena)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nazivTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(naziv))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(autor)
                            .addComponent(autorCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(datum)
                            .addComponent(datumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(porukaLbl)
                    .addComponent(vrijemeLbl))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void povratakBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_povratakBttnActionPerformed
        this.dispose();
    }//GEN-LAST:event_povratakBttnActionPerformed

    private void dodajBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dodajBttnActionPerformed
        porukaLbl.setText("");
        entitet = new Djelo();

        postaviVrijednostiUEntitet();

        obrada.setEntitet(entitet);
        try {
            obrada.create();
            ucitajPodatke();
            ocistiPolja();
        } catch (SkrbinaException ex) {
            porukaLbl.setText(ex.getPoruka());
        }
    }//GEN-LAST:event_dodajBttnActionPerformed

    private void izmijeniBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_izmijeniBttnActionPerformed
        entitet = djelaLst.getSelectedValue();
        if (entitet == null) {
            return;
        }

        postaviVrijednostiUEntitet();

        try {
            obrada.update();
            ucitajPodatke();
            ocistiPolja();
        } catch (SkrbinaException e) {
            porukaLbl.setText(e.getPoruka());
        }
    }//GEN-LAST:event_izmijeniBttnActionPerformed

    private void obrisiBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obrisiBttnActionPerformed
        entitet = djelaLst.getSelectedValue();
        if (entitet == null) {
            return;
        }

        obrada.setEntitet(entitet);

        try {
            obrada.delete();
            ucitajPodatke();
            ocistiPolja();
        } catch (SkrbinaException e) {
            porukaLbl.setText(e.getPoruka());
        }
    }//GEN-LAST:event_obrisiBttnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ocistiPolja();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void djelaLstValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_djelaLstValueChanged
        pregledLbl.setIcon(dfltImg);
        pregledLbl.setText("");
        try {
            String slika = djelaLst.getSelectedValue().getNaziv();
            img = new ImageIcon(getClass().getResource("/" + slika + ".jpg"));
            if (img != null) {
                pregledLbl.setIcon(img);
                pregledLbl.setText("");
            } else {
                pregledLbl.setIcon(dfltImg);
                pregledLbl.setText("");

            }
        } catch (Exception x) {
            //porukaLbl.setText(x.getMessage());
        }

        if (djelaLst.isSelectionEmpty()) {
            izmijeniBttn.setEnabled(false);
            obrisiBttn.setEnabled(false);
        } else {
            izmijeniBttn.setEnabled(true);
            obrisiBttn.setEnabled(true);
        }

        if (evt.getValueIsAdjusting()) {
            return;
        }

        entitet = djelaLst.getSelectedValue();
        if (entitet == null) {
            return;
        }
        nazivTxt.setText(entitet.getNaziv());
        DefaultComboBoxModel<Autor> auth = (DefaultComboBoxModel<Autor>) autorCmb.getModel();
        for (int i = 0; i < auth.getSize(); i++) {
            if (auth.getElementAt(i).getId().equals(entitet.getAutor().getId())) {
                autorCmb.setSelectedIndex(i);
                break;
            }
        }
        datumTxt.setText(entitet.getDatum());
        opisTxt.setText(entitet.getOpis());
        cijenaTxt.setText(entitet.getCijena().toString());
    }//GEN-LAST:event_djelaLstValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Djela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Djela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Djela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Djela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Djela().setVisible(true);
            }
        });
    }

    private void ucitajPodatke() {
        DefaultListModel<Djelo> d = new DefaultListModel<>();
        obrada.getPodaci().forEach(k -> d.addElement(k));
        djelaLst.setModel(d);
    }

    private void ocistiPolja() {
        pregledLbl.setIcon(new ImageIcon(getClass().getResource("/default.jpg")));
        pregledLbl.setText("");
        djelaLst.clearSelection();
        nazivTxt.setText("");
        autorCmb.setSelectedIndex(0);
        datumTxt.setText("");
        opisTxt.setText("");
        cijenaTxt.setText("");
    }

    private void postaviVrijednostiUEntitet() {
        entitet.setNaziv(nazivTxt.getText());
        entitet.setAutor((Autor) autorCmb.getSelectedItem());
        entitet.setDatum(datumTxt.getText());
        entitet.setOpis(opisTxt.getText());
        entitet.setCijena(Double.parseDouble(cijenaTxt.getText()));
        obrada.setEntitet(entitet);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel autor;
    private javax.swing.JComboBox<Autor> autorCmb;
    private javax.swing.JLabel cijena;
    private javax.swing.JTextField cijenaTxt;
    private javax.swing.JLabel datum;
    private javax.swing.JTextField datumTxt;
    private javax.swing.JList<Djelo> djelaLst;
    private javax.swing.JButton dodajBttn;
    private javax.swing.JButton izmijeniBttn;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel naziv;
    private javax.swing.JTextField nazivTxt;
    private javax.swing.JButton obrisiBttn;
    private javax.swing.JLabel opis;
    private javax.swing.JTextArea opisTxt;
    private javax.swing.JLabel porukaLbl;
    private javax.swing.JButton povratakBttn;
    private javax.swing.JLabel pregledLbl;
    private javax.swing.JLabel vrijemeLbl;
    // End of variables declaration//GEN-END:variables

    private void checkAndEmpty() {
        if (djelaLst.isSelectionEmpty()) {
            obrisiBttn.setEnabled(false);
            izmijeniBttn.setEnabled(false);
        }
        nazivTxt.setText("");
        datumTxt.setText("");
        opisTxt.setText("");
        autorCmb.setSelectedIndex(-1);
        porukaLbl.setText("");
        cijenaTxt.setText("");

        DefaultComboBoxModel<Autor> mp = new DefaultComboBoxModel<>();
        new ObradaAutor().getPodaci().forEach(p -> {
            mp.addElement(p);
        });
        autorCmb.setRenderer(new OsobaCellRenderer());
        autorCmb.setModel(mp);

        djelaLst.setSelectionMode(DefaultListSelectionModel.SINGLE_SELECTION);
        pregledLbl.setIcon(new ImageIcon(getClass().getResource("/default.jpg")));
        if (djelaLst.isSelectionEmpty()) {
            izmijeniBttn.setEnabled(false);
            obrisiBttn.setEnabled(false);
        }
    }
}
