/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hr.skrbina.edunovazavrsnigalerija.view;

/**
 *
 * @author Hrvoje
 */
public class Izbornik extends javax.swing.JFrame {

    /**
     * Creates new form Izbornik
     */
    public Izbornik() {    
        initComponents();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        izbornik = new javax.swing.JTabbedPane();
        galerija = new javax.swing.JPanel();
        izlozbe_btn = new javax.swing.JButton();
        djela_btn = new javax.swing.JButton();
        logo = new javax.swing.JLabel();
        izlazBtrn = new javax.swing.JButton();
        administracija = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        logo1 = new javax.swing.JLabel();
        osobeBttn = new javax.swing.JButton();
        autoriBttn = new javax.swing.JButton();
        izlazBttn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Galerija Exclusive");

        izbornik.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        izbornik.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        izbornik.setMaximumSize(new java.awt.Dimension(678, 100));
        izbornik.setMinimumSize(new java.awt.Dimension(678, 100));

        izlozbe_btn.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        izlozbe_btn.setText("Izložbe");
        izlozbe_btn.setMaximumSize(new java.awt.Dimension(140, 66));
        izlozbe_btn.setMinimumSize(new java.awt.Dimension(140, 66));
        izlozbe_btn.setPreferredSize(new java.awt.Dimension(140, 66));
        izlozbe_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                izlozbe_btnActionPerformed(evt);
            }
        });

        djela_btn.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        djela_btn.setText("Djela");
        djela_btn.setMaximumSize(new java.awt.Dimension(140, 66));
        djela_btn.setMinimumSize(new java.awt.Dimension(140, 66));
        djela_btn.setPreferredSize(new java.awt.Dimension(140, 66));
        djela_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                djela_btnActionPerformed(evt);
            }
        });

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/splash_gallery.png"))); // NOI18N

        izlazBtrn.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        izlazBtrn.setText("Izlaz");
        izlazBtrn.setMaximumSize(new java.awt.Dimension(140, 66));
        izlazBtrn.setMinimumSize(new java.awt.Dimension(140, 66));
        izlazBtrn.setPreferredSize(new java.awt.Dimension(140, 66));
        izlazBtrn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                izlazBtrnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout galerijaLayout = new javax.swing.GroupLayout(galerija);
        galerija.setLayout(galerijaLayout);
        galerijaLayout.setHorizontalGroup(
            galerijaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(galerijaLayout.createSequentialGroup()
                .addGroup(galerijaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(galerijaLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(djela_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(izlozbe_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(izlazBtrn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(galerijaLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(logo)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        galerijaLayout.setVerticalGroup(
            galerijaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(galerijaLayout.createSequentialGroup()
                .addComponent(logo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(galerijaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(izlozbe_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(djela_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(izlazBtrn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        izbornik.addTab("Galerija", galerija);

        jButton4.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        jButton4.setText("Korisnici");
        jButton4.setMaximumSize(new java.awt.Dimension(156, 30));
        jButton4.setMinimumSize(new java.awt.Dimension(156, 30));
        jButton4.setPreferredSize(new java.awt.Dimension(156, 30));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        jButton5.setText("Transakcije");
        jButton5.setMaximumSize(new java.awt.Dimension(156, 30));
        jButton5.setMinimumSize(new java.awt.Dimension(156, 30));
        jButton5.setPreferredSize(new java.awt.Dimension(156, 30));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        jButton3.setText("Kustosi");
        jButton3.setMaximumSize(new java.awt.Dimension(156, 30));
        jButton3.setMinimumSize(new java.awt.Dimension(156, 30));
        jButton3.setPreferredSize(new java.awt.Dimension(156, 30));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        logo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/splash_gallery.png"))); // NOI18N

        osobeBttn.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        osobeBttn.setText("Osobe");
        osobeBttn.setMaximumSize(new java.awt.Dimension(156, 30));
        osobeBttn.setMinimumSize(new java.awt.Dimension(156, 30));
        osobeBttn.setPreferredSize(new java.awt.Dimension(156, 30));
        osobeBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                osobeBttnActionPerformed(evt);
            }
        });

        autoriBttn.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        autoriBttn.setText("Autori");
        autoriBttn.setMaximumSize(new java.awt.Dimension(156, 30));
        autoriBttn.setMinimumSize(new java.awt.Dimension(156, 30));
        autoriBttn.setPreferredSize(new java.awt.Dimension(156, 30));
        autoriBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autoriBttnActionPerformed(evt);
            }
        });

        izlazBttn.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        izlazBttn.setText("Izlaz");
        izlazBttn.setMaximumSize(new java.awt.Dimension(156, 30));
        izlazBttn.setMinimumSize(new java.awt.Dimension(156, 30));
        izlazBttn.setPreferredSize(new java.awt.Dimension(156, 30));
        izlazBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                izlazBttnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout administracijaLayout = new javax.swing.GroupLayout(administracija);
        administracija.setLayout(administracijaLayout);
        administracijaLayout.setHorizontalGroup(
            administracijaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(administracijaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(administracijaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(administracijaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(osobeBttn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(administracijaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(izlazBttn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(autoriBttn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(63, 63, 63))
            .addGroup(administracijaLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(logo1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        administracijaLayout.setVerticalGroup(
            administracijaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(administracijaLayout.createSequentialGroup()
                .addComponent(logo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(administracijaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(administracijaLayout.createSequentialGroup()
                        .addGroup(administracijaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(autoriBttn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(administracijaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(osobeBttn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(izlazBttn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        izbornik.addTab("Administracija", administracija);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(izbornik, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(izbornik, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void djela_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_djela_btnActionPerformed
        Djela dj = new Djela();
        dj.setVisible(true);
        dj.setLocationRelativeTo(null);
    }//GEN-LAST:event_djela_btnActionPerformed

    private void izlozbe_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_izlozbe_btnActionPerformed
        Izlozbe iz = new Izlozbe();
        iz.setVisible(true);
        iz.setLocationRelativeTo(null);   
    }//GEN-LAST:event_izlozbe_btnActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Korisnici korisnici = new Korisnici();
        korisnici.setVisible(true);
        korisnici.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void osobeBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_osobeBttnActionPerformed
        Osobe osb = new Osobe();
        osb.setVisible(true);
        osb.setLocationRelativeTo(null);
    }//GEN-LAST:event_osobeBttnActionPerformed

    private void izlazBtrnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_izlazBtrnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_izlazBtrnActionPerformed

    private void izlazBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_izlazBttnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_izlazBttnActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Kustosi kust = new Kustosi();
        kust.setVisible(true);
        kust.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void autoriBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autoriBttnActionPerformed
        Autori aut = new Autori();
        aut.setVisible(true);
        aut.setLocationRelativeTo(null);
    }//GEN-LAST:event_autoriBttnActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Transakcije trs = new Transakcije();
        trs.setVisible(true);
        trs.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton5ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel administracija;
    private javax.swing.JButton autoriBttn;
    private javax.swing.JButton djela_btn;
    private javax.swing.JPanel galerija;
    private javax.swing.JTabbedPane izbornik;
    private javax.swing.JButton izlazBtrn;
    private javax.swing.JButton izlazBttn;
    private javax.swing.JButton izlozbe_btn;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel logo1;
    private javax.swing.JButton osobeBttn;
    // End of variables declaration//GEN-END:variables
}
