/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hr.skrbina.edunovazavrsnigalerija.view;

import com.github.javafaker.Faker;
import hr.skrbina.edunovazavrsnigalerija.controller.ObradaKustos;
import hr.skrbina.edunovazavrsnigalerija.model.Kustos;
import hr.skrbina.edunovazavrsnigalerija.utility.DatumIVrijeme;
import hr.skrbina.edunovazavrsnigalerija.utility.Iban;
import hr.skrbina.edunovazavrsnigalerija.utility.Oib;
import hr.skrbina.edunovazavrsnigalerija.utility.SkrbinaException;
import java.awt.event.ActionEvent;
import java.text.SimpleDateFormat;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.DefaultListSelectionModel;
import javax.swing.Timer;

/**
 *
 * @author Hrvoje
 */
public class Kustosi extends javax.swing.JFrame {

    private final ObradaKustos obrada;
    private Kustos entitet;

    /**
     * Creates new form Kustosi
     */
    public Kustosi() {
        initComponents();
        obrada = new ObradaKustos();
        setTitle(Aplikacija.NASLOV_APP + " - Kustosi");
        defaultStart();
        kustosLst.setCellRenderer(new OsobaCellRenderer());
        kustosLst.setSelectionMode(DefaultListSelectionModel.SINGLE_SELECTION);

        SimpleDateFormat myTime = new SimpleDateFormat("HH:mm:ss" + "    " + "dd.MM.YYYY.");
        Timer SimpleTimer = new Timer(1000, (ActionEvent e) -> {
            vrijemeLbl.setText(myTime.format(new Date()));
        });
        SimpleTimer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ime = new javax.swing.JLabel();
        prezime = new javax.swing.JLabel();
        datum = new javax.swing.JLabel();
        oib = new javax.swing.JLabel();
        mjesto = new javax.swing.JLabel();
        iban = new javax.swing.JLabel();
        kontakt = new javax.swing.JLabel();
        imeTxt = new javax.swing.JTextField();
        prezimeTxt = new javax.swing.JTextField();
        oibTxt = new javax.swing.JTextField();
        mrTxt = new javax.swing.JTextField();
        ibanTxt = new javax.swing.JTextField();
        kontaktTxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        kustosLst = new javax.swing.JList<>();
        dodajBttn = new javax.swing.JButton();
        izmijeniBttn = new javax.swing.JButton();
        obrisiBttn = new javax.swing.JButton();
        povratakBttn = new javax.swing.JButton();
        traziTxt = new javax.swing.JTextField();
        traziBttn = new javax.swing.JButton();
        porukaLbl = new javax.swing.JLabel();
        ocistiBttn = new javax.swing.JButton();
        oibBttn = new javax.swing.JButton();
        datumTxt = new javax.swing.JTextField();
        generirajIban = new javax.swing.JButton();
        izlozbeTxt = new javax.swing.JTextField();
        izlozba = new javax.swing.JLabel();
        vrijemeLbl = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(764, 264));
        setMinimumSize(new java.awt.Dimension(764, 264));
        setResizable(false);

        ime.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        ime.setText("Ime:");

        prezime.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        prezime.setText("Prezime:");

        datum.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        datum.setText("Datum rođenja:");

        oib.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        oib.setText("OIB:");

        mjesto.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        mjesto.setText("Mjesto rođenja:");

        iban.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        iban.setText("IBAN:");

        kontakt.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        kontakt.setText("Kontakt:");

        imeTxt.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        imeTxt.setText("jTextField1");
        imeTxt.setMaximumSize(new java.awt.Dimension(461, 30));
        imeTxt.setMinimumSize(new java.awt.Dimension(461, 30));
        imeTxt.setPreferredSize(new java.awt.Dimension(461, 30));

        prezimeTxt.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        prezimeTxt.setText("jTextField2");
        prezimeTxt.setMaximumSize(new java.awt.Dimension(461, 30));
        prezimeTxt.setMinimumSize(new java.awt.Dimension(461, 30));
        prezimeTxt.setPreferredSize(new java.awt.Dimension(461, 30));

        oibTxt.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        oibTxt.setText("jTextField3");
        oibTxt.setMaximumSize(new java.awt.Dimension(300, 30));
        oibTxt.setMinimumSize(new java.awt.Dimension(300, 30));
        oibTxt.setPreferredSize(new java.awt.Dimension(300, 30));

        mrTxt.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        mrTxt.setText("jTextField4");
        mrTxt.setMaximumSize(new java.awt.Dimension(461, 30));
        mrTxt.setMinimumSize(new java.awt.Dimension(461, 30));
        mrTxt.setPreferredSize(new java.awt.Dimension(461, 30));

        ibanTxt.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        ibanTxt.setText("jTextField5");
        ibanTxt.setMaximumSize(new java.awt.Dimension(321, 30));
        ibanTxt.setMinimumSize(new java.awt.Dimension(321, 30));
        ibanTxt.setPreferredSize(new java.awt.Dimension(321, 30));

        kontaktTxt.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        kontaktTxt.setText("jTextField6");
        kontaktTxt.setMaximumSize(new java.awt.Dimension(461, 30));
        kontaktTxt.setMinimumSize(new java.awt.Dimension(461, 30));
        kontaktTxt.setPreferredSize(new java.awt.Dimension(461, 30));

        jScrollPane1.setMaximumSize(new java.awt.Dimension(268, 283));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(268, 283));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(268, 283));

        kustosLst.setFont(new java.awt.Font("Georgia", 2, 14)); // NOI18N
        kustosLst.setMaximumSize(new java.awt.Dimension(250, 220));
        kustosLst.setMinimumSize(new java.awt.Dimension(250, 220));
        kustosLst.setPreferredSize(new java.awt.Dimension(250, 220));
        kustosLst.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                kustosLstValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(kustosLst);

        dodajBttn.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        dodajBttn.setText("Dodaj");
        dodajBttn.setMaximumSize(new java.awt.Dimension(112, 30));
        dodajBttn.setMinimumSize(new java.awt.Dimension(112, 30));
        dodajBttn.setPreferredSize(new java.awt.Dimension(112, 30));
        dodajBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dodajBttnActionPerformed(evt);
            }
        });

        izmijeniBttn.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        izmijeniBttn.setText("Izmijeni");
        izmijeniBttn.setMaximumSize(new java.awt.Dimension(112, 30));
        izmijeniBttn.setMinimumSize(new java.awt.Dimension(112, 30));
        izmijeniBttn.setPreferredSize(new java.awt.Dimension(112, 30));
        izmijeniBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                izmijeniBttnActionPerformed(evt);
            }
        });

        obrisiBttn.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        obrisiBttn.setText("Obriši");
        obrisiBttn.setMaximumSize(new java.awt.Dimension(112, 30));
        obrisiBttn.setMinimumSize(new java.awt.Dimension(112, 30));
        obrisiBttn.setPreferredSize(new java.awt.Dimension(112, 30));
        obrisiBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obrisiBttnActionPerformed(evt);
            }
        });

        povratakBttn.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        povratakBttn.setText("Povratak");
        povratakBttn.setMaximumSize(new java.awt.Dimension(112, 30));
        povratakBttn.setMinimumSize(new java.awt.Dimension(112, 30));
        povratakBttn.setPreferredSize(new java.awt.Dimension(112, 30));
        povratakBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                povratakBttnActionPerformed(evt);
            }
        });

        traziTxt.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        traziTxt.setText("trazi");
        traziTxt.setMaximumSize(new java.awt.Dimension(180, 30));
        traziTxt.setMinimumSize(new java.awt.Dimension(180, 30));
        traziTxt.setPreferredSize(new java.awt.Dimension(180, 30));

        traziBttn.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        traziBttn.setText("Traži");
        traziBttn.setMaximumSize(new java.awt.Dimension(84, 30));
        traziBttn.setMinimumSize(new java.awt.Dimension(84, 30));
        traziBttn.setPreferredSize(new java.awt.Dimension(84, 30));
        traziBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                traziBttnActionPerformed(evt);
            }
        });

        porukaLbl.setFont(new java.awt.Font("Georgia", 2, 14)); // NOI18N
        porukaLbl.setText("jLabel8");

        ocistiBttn.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        ocistiBttn.setText("Očisti");
        ocistiBttn.setMaximumSize(new java.awt.Dimension(112, 30));
        ocistiBttn.setMinimumSize(new java.awt.Dimension(112, 30));
        ocistiBttn.setPreferredSize(new java.awt.Dimension(112, 30));
        ocistiBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ocistiBttnActionPerformed(evt);
            }
        });

        oibBttn.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        oibBttn.setText("Generiraj OIB");
        oibBttn.setMaximumSize(new java.awt.Dimension(155, 30));
        oibBttn.setMinimumSize(new java.awt.Dimension(155, 30));
        oibBttn.setPreferredSize(new java.awt.Dimension(155, 30));
        oibBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oibBttnActionPerformed(evt);
            }
        });

        datumTxt.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        datumTxt.setText("jTextField1");
        datumTxt.setMaximumSize(new java.awt.Dimension(461, 30));
        datumTxt.setMinimumSize(new java.awt.Dimension(461, 30));
        datumTxt.setPreferredSize(new java.awt.Dimension(461, 30));

        generirajIban.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        generirajIban.setText("Generiraj IBAN");
        generirajIban.setMaximumSize(new java.awt.Dimension(155, 30));
        generirajIban.setMinimumSize(new java.awt.Dimension(155, 30));
        generirajIban.setPreferredSize(new java.awt.Dimension(155, 30));
        generirajIban.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generirajIbanActionPerformed(evt);
            }
        });

        izlozbeTxt.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        izlozbeTxt.setText("jTextField1");
        izlozbeTxt.setMaximumSize(new java.awt.Dimension(461, 30));
        izlozbeTxt.setMinimumSize(new java.awt.Dimension(461, 30));
        izlozbeTxt.setPreferredSize(new java.awt.Dimension(461, 30));

        izlozba.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        izlozba.setText("Izložba:");

        vrijemeLbl.setFont(new java.awt.Font("Georgia", 2, 14)); // NOI18N

        jButton1.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jButton1.setText("Generiraj");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(traziTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(traziBttn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(vrijemeLbl)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(kontakt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(kontaktTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mjesto)
                            .addComponent(iban))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(ibanTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(generirajIban, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(mrTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(izlozba)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(izlozbeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(prezime)
                                    .addComponent(ime)
                                    .addComponent(datum)
                                    .addComponent(oib))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(oibTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(oibBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGap(0, 0, Short.MAX_VALUE)
                                            .addComponent(imeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(datumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                    .addComponent(prezimeTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(porukaLbl))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(236, 236, 236)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(povratakBttn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(dodajBttn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(izmijeniBttn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(obrisiBttn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ocistiBttn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(traziTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(traziBttn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ime)
                            .addComponent(imeTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(prezimeTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(prezime))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(datumTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(datum))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(oib)
                                .addComponent(oibBttn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(oibTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mrTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mjesto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(generirajIban, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(ibanTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(iban)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kontaktTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kontakt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(izlozbeTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(izlozba))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                            .addComponent(izmijeniBttn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(obrisiBttn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ocistiBttn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dodajBttn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(povratakBttn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(porukaLbl)
                    .addComponent(vrijemeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void povratakBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_povratakBttnActionPerformed
        this.dispose();
    }//GEN-LAST:event_povratakBttnActionPerformed

    private void dodajBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dodajBttnActionPerformed
        porukaLbl.setText("");
        entitet = new Kustos();

        postaviVrijednostiUEntitet();

        obrada.setEntitet(entitet);
        try {
            obrada.create();
            ucitajPodatke();
            defaultStart();
        } catch (SkrbinaException ex) {
            porukaLbl.setText(ex.getPoruka());
        }
    }//GEN-LAST:event_dodajBttnActionPerformed

    private void izmijeniBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_izmijeniBttnActionPerformed
        entitet = kustosLst.getSelectedValue();
        if (entitet == null) {
            return;
        }
        postaviVrijednostiUEntitet();

        try {
            obrada.update();
            ucitajPodatke();
            defaultStart();
        } catch (SkrbinaException e) {
            porukaLbl.setText(e.getPoruka());
        }
    }//GEN-LAST:event_izmijeniBttnActionPerformed

    private void obrisiBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obrisiBttnActionPerformed
        entitet = kustosLst.getSelectedValue();
        if (entitet == null) {
            return;
        }

        obrada.setEntitet(entitet);

        try {
            obrada.delete();
            ucitajPodatke();
            defaultStart();
        } catch (SkrbinaException e) {
            porukaLbl.setText(e.getPoruka());
        }
    }//GEN-LAST:event_obrisiBttnActionPerformed

    private void traziBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_traziBttnActionPerformed
        if (traziTxt.getText().isEmpty()) {
            defaultStart();
        } else {
            ucitajZaTrazi();
        }
    }//GEN-LAST:event_traziBttnActionPerformed

    private void kustosLstValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_kustosLstValueChanged
        entitet = kustosLst.getSelectedValue();
        if (entitet == null) {
            return;
        }

        if (!kustosLst.isSelectionEmpty()) {
            obrisiBttn.setEnabled(true);
            izmijeniBttn.setEnabled(true);
        }

        if (evt.getValueIsAdjusting()) {
            return;
        }

        imeTxt.setText(entitet.getIme());
        prezimeTxt.setText(entitet.getPrezime());
        datumTxt.setText(entitet.getRodjendan());
        oibTxt.setText(entitet.getOib());
        mrTxt.setText(entitet.getMjesto_Rodjenja());
        ibanTxt.setText(entitet.getIBAN());
        kontaktTxt.setText(entitet.getKontakt());
        if (entitet.getIzlozba() == null) {
            izlozbeTxt.setText("");
        } else {
            izlozbeTxt.setText(entitet.getIzlozba().getNaziv());
        }
    }//GEN-LAST:event_kustosLstValueChanged

    private void ocistiBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ocistiBttnActionPerformed
        defaultStart();
    }//GEN-LAST:event_ocistiBttnActionPerformed

    private void oibBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oibBttnActionPerformed
        oibTxt.setText(Oib.getOibIiCentrala());
    }//GEN-LAST:event_oibBttnActionPerformed

    private void generirajIbanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generirajIbanActionPerformed
        ibanTxt.setText(Iban.getIbanIiCentrala());
    }//GEN-LAST:event_generirajIbanActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        generirajPodatke();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kustosi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kustosi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kustosi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kustosi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Kustosi().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel datum;
    private javax.swing.JTextField datumTxt;
    private javax.swing.JButton dodajBttn;
    private javax.swing.JButton generirajIban;
    private javax.swing.JLabel iban;
    private javax.swing.JTextField ibanTxt;
    private javax.swing.JLabel ime;
    private javax.swing.JTextField imeTxt;
    private javax.swing.JLabel izlozba;
    private javax.swing.JTextField izlozbeTxt;
    private javax.swing.JButton izmijeniBttn;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel kontakt;
    private javax.swing.JTextField kontaktTxt;
    private javax.swing.JList<Kustos> kustosLst;
    private javax.swing.JLabel mjesto;
    private javax.swing.JTextField mrTxt;
    private javax.swing.JButton obrisiBttn;
    private javax.swing.JButton ocistiBttn;
    private javax.swing.JLabel oib;
    private javax.swing.JButton oibBttn;
    private javax.swing.JTextField oibTxt;
    private javax.swing.JLabel porukaLbl;
    private javax.swing.JButton povratakBttn;
    private javax.swing.JLabel prezime;
    private javax.swing.JTextField prezimeTxt;
    private javax.swing.JButton traziBttn;
    private javax.swing.JTextField traziTxt;
    private javax.swing.JLabel vrijemeLbl;
    // End of variables declaration//GEN-END:variables

    private void ucitajPodatke() {
        DefaultListModel<Kustos> m = new DefaultListModel<>();
        obrada.getPodaci().forEach(r -> m.addElement(r));
        kustosLst.setModel(m);
    }

    private void ucitajZaTrazi() {
        DefaultListModel<Kustos> m = new DefaultListModel<>();
        obrada.getPodaci(traziTxt.getText()).forEach(k -> m.addElement(k));
        kustosLst.setModel(m);
    }

    private void defaultStart() {
        ucitajPodatke();
        kustosLst.clearSelection();
        traziTxt.setText("");
        imeTxt.setText("");
        prezimeTxt.setText("");
        datumTxt.setText("");
        oibTxt.setText("");
        mrTxt.setText("");
        ibanTxt.setText("");
        kontaktTxt.setText("");
        porukaLbl.setText("");
        izlozbeTxt.setText("");
        traziTxt.requestFocus();
        if (kustosLst.isSelectionEmpty()) {
            izmijeniBttn.setEnabled(false);
            obrisiBttn.setEnabled(false);
        }
    }

    private void postaviVrijednostiUEntitet() {
        entitet.setIme(imeTxt.getText());
        entitet.setPrezime(prezimeTxt.getText());
        entitet.setRodjendan(datumTxt.getText());
        entitet.setOib(oibTxt.getText());
        entitet.setMjesto_Rodjenja(mrTxt.getText());
        entitet.setIBAN(ibanTxt.getText());
        entitet.setKontakt(kontaktTxt.getText());
        entitet.setUlogaGalerija("kustos");
        obrada.setEntitet(entitet);
    }
    
    private void generirajPodatke() {
        Faker faker = new Faker();
        kustosLst.clearSelection();
        imeTxt.setText(faker.name().firstName());
        prezimeTxt.setText(faker.name().lastName());
        datumTxt.setText(DatumIVrijeme.generirajDatum().format(DateTimeFormatter.ofPattern("dd.MM.yyyy.")) +
                " " + DatumIVrijeme.generirajVrijeme());
        oibTxt.setText(Oib.getOibIiCentrala());
        mrTxt.setText(faker.address().fullAddress());
        ibanTxt.setText(Iban.getIbanIiCentrala());
        kontaktTxt.setText(imeTxt.getText().toLowerCase().charAt(0) + prezimeTxt.getText().toLowerCase() +
                "@" + faker.internet().domainName());
        porukaLbl.setText("");
        dodajBttn.requestFocus();
        if (kustosLst.isSelectionEmpty()) {
            izmijeniBttn.setEnabled(false);
            obrisiBttn.setEnabled(false);
        }
    }
}