/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hr.skrbina.edunovazavrsnigalerija.view;

import hr.skrbina.edunovazavrsnigalerija.controller.ObradaKustos;
import hr.skrbina.edunovazavrsnigalerija.model.Kustos;
import hr.skrbina.edunovazavrsnigalerija.utility.SkrbinaException;
import javax.swing.DefaultListModel;
import javax.swing.DefaultListSelectionModel;
import javax.swing.ImageIcon;

/**
 *
 * @author Hrvoje
 */
public class Kustosi extends javax.swing.JFrame {
    
    private ObradaKustos obrada;
    private Kustos entitet;
    
    /**
     * Creates new form Kustosi
     */
    public Kustosi() {
        initComponents();
        obrada = new ObradaKustos();
        setTitle("Gallery Exclusive - Kustosi");
        ucitajPodatke();
        
        kustosLst.setSelectionMode(DefaultListSelectionModel.SINGLE_SELECTION);
        if (kustosLst.isSelectionEmpty()) {
            obrisiBttn.setEnabled(false);
            izmijeniBttn.setEnabled(false);
        }
        
        slikaLbl.setIcon(new ImageIcon(getClass().getResource("/osoba_def.jpg")));
        traziTxt.requestFocus();
        
        emptyFields();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        slikaLbl = new javax.swing.JLabel();
        ime = new javax.swing.JLabel();
        prezime = new javax.swing.JLabel();
        datum = new javax.swing.JLabel();
        oib = new javax.swing.JLabel();
        mjesto = new javax.swing.JLabel();
        iban = new javax.swing.JLabel();
        kontakt = new javax.swing.JLabel();
        imeTxt = new javax.swing.JTextField();
        prezimeTxt = new javax.swing.JTextField();
        datumTxt = new javax.swing.JFormattedTextField();
        oibTxt = new javax.swing.JTextField();
        mrTxt = new javax.swing.JTextField();
        ibanTxt = new javax.swing.JTextField();
        kontaktTxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        kustosLst = new javax.swing.JList<>();
        dodajBttn = new javax.swing.JButton();
        izmijeniBttn = new javax.swing.JButton();
        obrisiBttn = new javax.swing.JButton();
        povratakBttn = new javax.swing.JButton();
        traziTxt = new javax.swing.JTextField();
        traziBttn = new javax.swing.JButton();
        porukaLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        slikaLbl.setMaximumSize(new java.awt.Dimension(150, 150));
        slikaLbl.setMinimumSize(new java.awt.Dimension(150, 150));
        slikaLbl.setPreferredSize(new java.awt.Dimension(150, 150));

        ime.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        ime.setText("Ime:");

        prezime.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        prezime.setText("Prezime:");

        datum.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        datum.setText("Datum rođenja:");

        oib.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        oib.setText("OIB:");

        mjesto.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        mjesto.setText("Mjesto rođenja:");

        iban.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        iban.setText("IBAN:");

        kontakt.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        kontakt.setText("Kontakt:");

        imeTxt.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        imeTxt.setText("jTextField1");

        prezimeTxt.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        prezimeTxt.setText("jTextField2");

        datumTxt.setText("jFormattedTextField1");
        datumTxt.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N

        oibTxt.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        oibTxt.setText("jTextField3");

        mrTxt.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        mrTxt.setText("jTextField4");

        ibanTxt.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        ibanTxt.setText("jTextField5");

        kontaktTxt.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        kontaktTxt.setText("jTextField6");

        kustosLst.setFont(new java.awt.Font("Georgia", 2, 14)); // NOI18N
        kustosLst.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                kustosLstValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(kustosLst);

        dodajBttn.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        dodajBttn.setText("Dodaj");
        dodajBttn.setMaximumSize(new java.awt.Dimension(110, 45));
        dodajBttn.setMinimumSize(new java.awt.Dimension(110, 45));
        dodajBttn.setPreferredSize(new java.awt.Dimension(110, 45));
        dodajBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dodajBttnActionPerformed(evt);
            }
        });

        izmijeniBttn.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        izmijeniBttn.setText("Izmijeni");
        izmijeniBttn.setMaximumSize(new java.awt.Dimension(110, 45));
        izmijeniBttn.setMinimumSize(new java.awt.Dimension(110, 45));
        izmijeniBttn.setPreferredSize(new java.awt.Dimension(110, 45));
        izmijeniBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                izmijeniBttnActionPerformed(evt);
            }
        });

        obrisiBttn.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        obrisiBttn.setText("Obriši");
        obrisiBttn.setMaximumSize(new java.awt.Dimension(110, 45));
        obrisiBttn.setMinimumSize(new java.awt.Dimension(110, 45));
        obrisiBttn.setPreferredSize(new java.awt.Dimension(110, 45));
        obrisiBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obrisiBttnActionPerformed(evt);
            }
        });

        povratakBttn.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        povratakBttn.setText("Povratak");
        povratakBttn.setMaximumSize(new java.awt.Dimension(110, 45));
        povratakBttn.setMinimumSize(new java.awt.Dimension(110, 45));
        povratakBttn.setPreferredSize(new java.awt.Dimension(110, 45));
        povratakBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                povratakBttnActionPerformed(evt);
            }
        });

        traziTxt.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        traziTxt.setText("trazi");

        traziBttn.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        traziBttn.setText("Traži");
        traziBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                traziBttnActionPerformed(evt);
            }
        });

        porukaLbl.setFont(new java.awt.Font("Georgia", 2, 14)); // NOI18N
        porukaLbl.setText("jLabel8");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(slikaLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(porukaLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(kontakt)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ime)
                                    .addComponent(prezime)
                                    .addComponent(datum)
                                    .addComponent(oib)
                                    .addComponent(mjesto)
                                    .addComponent(iban))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(imeTxt)
                                    .addComponent(prezimeTxt)
                                    .addComponent(datumTxt)
                                    .addComponent(oibTxt)
                                    .addComponent(mrTxt)
                                    .addComponent(ibanTxt)
                                    .addComponent(kontaktTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dodajBttn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(izmijeniBttn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(obrisiBttn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(povratakBttn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(traziBttn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(traziTxt))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(traziTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(traziBttn)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ime)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(imeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(prezimeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(prezime))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(datumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(datum))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(oibTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(oib))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(mrTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(mjesto))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(ibanTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(iban)))
                                    .addComponent(slikaLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(kontaktTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(kontakt)
                                    .addComponent(porukaLbl))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(povratakBttn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(obrisiBttn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(izmijeniBttn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dodajBttn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void povratakBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_povratakBttnActionPerformed
        this.dispose();
    }//GEN-LAST:event_povratakBttnActionPerformed

    private void dodajBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dodajBttnActionPerformed
        porukaLbl.setText("");
        entitet = new Kustos();

        postaviVrijednostiUEntitet();

        obrada.setEntitet(entitet);
        try {
            obrada.create();
            ucitajPodatke();
            emptyFields();
        } catch (SkrbinaException ex) {
            porukaLbl.setText(ex.getPoruka());
        }
    }//GEN-LAST:event_dodajBttnActionPerformed

    private void izmijeniBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_izmijeniBttnActionPerformed
        entitet = kustosLst.getSelectedValue();
        if (entitet == null) {
            return;
        }
        postaviVrijednostiUEntitet();

        try {
            obrada.update();
            ucitajPodatke();
            emptyFields();
        } catch (SkrbinaException e) {
            porukaLbl.setText(e.getPoruka());
        }
    }//GEN-LAST:event_izmijeniBttnActionPerformed

    private void obrisiBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obrisiBttnActionPerformed
        entitet = kustosLst.getSelectedValue();
        if (entitet == null) {
            return;
        }

        obrada.setEntitet(entitet);

        try {
            obrada.delete();
            ucitajPodatke();
            emptyFields();
        } catch (SkrbinaException e) {
            porukaLbl.setText(e.getPoruka());
        }
    }//GEN-LAST:event_obrisiBttnActionPerformed

    private void traziBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_traziBttnActionPerformed
        ucitajZaTrazi();
    }//GEN-LAST:event_traziBttnActionPerformed

    private void kustosLstValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_kustosLstValueChanged
        if (evt.getValueIsAdjusting()) {
            return;
        }

        entitet = kustosLst.getSelectedValue();
        if (entitet == null) {
            return;
        }
        imeTxt.setText(entitet.getIme());
        prezimeTxt.setText(entitet.getPrezime());
        datumTxt.setText(entitet.getRodjendan());
        oibTxt.setText(entitet.getOib());
        mrTxt.setText(entitet.getMjesto_Rodjenja());
        ibanTxt.setText(entitet.getIBAN());
        kontaktTxt.setText(entitet.getKontakt());
    }//GEN-LAST:event_kustosLstValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kustosi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kustosi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kustosi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kustosi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kustosi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel datum;
    private javax.swing.JFormattedTextField datumTxt;
    private javax.swing.JButton dodajBttn;
    private javax.swing.JLabel iban;
    private javax.swing.JTextField ibanTxt;
    private javax.swing.JLabel ime;
    private javax.swing.JTextField imeTxt;
    private javax.swing.JButton izmijeniBttn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel kontakt;
    private javax.swing.JTextField kontaktTxt;
    private javax.swing.JList<Kustos> kustosLst;
    private javax.swing.JLabel mjesto;
    private javax.swing.JTextField mrTxt;
    private javax.swing.JButton obrisiBttn;
    private javax.swing.JLabel oib;
    private javax.swing.JTextField oibTxt;
    private javax.swing.JLabel porukaLbl;
    private javax.swing.JButton povratakBttn;
    private javax.swing.JLabel prezime;
    private javax.swing.JTextField prezimeTxt;
    private javax.swing.JLabel slikaLbl;
    private javax.swing.JButton traziBttn;
    private javax.swing.JTextField traziTxt;
    // End of variables declaration//GEN-END:variables

    private void ucitajPodatke() {
        DefaultListModel<Kustos> m = new DefaultListModel<>();
        obrada.getPodaci().forEach(r -> m.addElement(r));
        kustosLst.setModel(m);
    }
    
    private void ucitajZaTrazi() {
        DefaultListModel<Kustos> m = new DefaultListModel<>();
        obrada.getPodaci(traziTxt.getText()).forEach(k -> m.addElement(k));
        kustosLst.setModel(m);
    }
    
    private void emptyFields() {
        traziTxt.setText("");
        imeTxt.setText("");
        prezimeTxt.setText("");
        datumTxt.setText("");
        oibTxt.setText("");
        mrTxt.setText("");
        ibanTxt.setText("");
        kontaktTxt.setText("");
        porukaLbl.setText("");
    }    
    
    private void postaviVrijednostiUEntitet() {
        entitet.setIme(imeTxt.getText());
        entitet.setPrezime(prezimeTxt.getText());
        entitet.setRodjendan(datumTxt.getText());
        entitet.setOib(oibTxt.getText());
        entitet.setMjesto_Rodjenja(mrTxt.getText());
        entitet.setIBAN(ibanTxt.getText());
        entitet.setKontakt(kontaktTxt.getText());
        entitet.setUlogaGalerija("kustos");

        obrada.setEntitet(entitet);
    }
}
