/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hr.skrbina.edunovazavrsnigalerija.view;

import hr.skrbina.edunovazavrsnigalerija.controller.ObradaAutor;
import hr.skrbina.edunovazavrsnigalerija.controller.ObradaDjelo;
import hr.skrbina.edunovazavrsnigalerija.controller.ObradaKorisnik;
import hr.skrbina.edunovazavrsnigalerija.model.Autor;
import hr.skrbina.edunovazavrsnigalerija.model.Djelo;
import hr.skrbina.edunovazavrsnigalerija.model.Korisnik;
import hr.skrbina.edunovazavrsnigalerija.utility.SkrbinaException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Hrvoje
 */
public class Transakcije extends javax.swing.JFrame {

    private final ObradaKorisnik obradaK;
    private Korisnik entitetK;

    private ObradaDjelo obradaD;
    private Djelo entitetD;

    private ImageIcon img;
    private final ImageIcon dfltImg = new ImageIcon(getClass().getResource("/default.jpg"));

    /**
     * Creates new form Transakcije
     */
    public Transakcije() {
        initComponents();
        setTitle("Gallery Exclusive - Transakcije");
        obradaK = new ObradaKorisnik();
        entitetK = new Korisnik();
        entitetD = new Djelo();
        setFirstDefault();
        emptyFields();
        ucitajKorisnike();
        prodajDflt.setIcon(new ImageIcon(getClass().getResource("/degasDflt.png")));
        kupLst.setCellRenderer(new DjeloCellRenderer());
        prodLst.setCellRenderer(new DjeloCellRenderer());
        korisniciLst.setCellRenderer(new OsobaCellRenderer());
        ucitajKupnju();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        korisniciLst = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        kupLst = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        prodLst = new javax.swing.JList<>();
        kupljena = new javax.swing.JLabel();
        prodana = new javax.swing.JLabel();
        transakcijaTabs = new javax.swing.JTabbedPane();
        kupnjaTab = new javax.swing.JPanel();
        pregledLbl = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        djelaLst = new javax.swing.JList<>();
        nazivK = new javax.swing.JLabel();
        autorK = new javax.swing.JLabel();
        datumK = new javax.swing.JLabel();
        nazivKTxt = new javax.swing.JTextField();
        opisK = new javax.swing.JLabel();
        traziKTxt = new javax.swing.JTextField();
        traziKBttn = new javax.swing.JButton();
        kupiBttn = new javax.swing.JButton();
        povratakKBttn = new javax.swing.JButton();
        cijenaKTxt = new javax.swing.JTextField();
        cijenaK = new javax.swing.JLabel();
        autorKCmb = new javax.swing.JComboBox<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        opisKTxt = new javax.swing.JTextArea();
        datumKTxt = new javax.swing.JTextField();
        prodajaTab = new javax.swing.JPanel();
        nazivP = new javax.swing.JLabel();
        nazivPTxt = new javax.swing.JTextField();
        datumPTxt = new javax.swing.JFormattedTextField();
        autorPCmb = new javax.swing.JComboBox<>();
        opisPTxt = new javax.swing.JTextField();
        datumP = new javax.swing.JLabel();
        autorP = new javax.swing.JLabel();
        opisP = new javax.swing.JLabel();
        prodajBttn = new javax.swing.JButton();
        ocistiBttn = new javax.swing.JButton();
        prodajDflt = new javax.swing.JLabel();
        povratakPBttn = new javax.swing.JButton();
        porukaLbl = new javax.swing.JLabel();
        cijenaPTxt = new javax.swing.JTextField();
        cijenaP = new javax.swing.JLabel();
        xx1 = new javax.swing.JLabel();
        a1 = new javax.swing.JLabel();
        a2 = new javax.swing.JLabel();
        a3 = new javax.swing.JLabel();
        a4 = new javax.swing.JLabel();
        a5 = new javax.swing.JLabel();
        a6 = new javax.swing.JLabel();
        a7 = new javax.swing.JLabel();
        a8 = new javax.swing.JLabel();
        a9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(759, 709));
        setMinimumSize(new java.awt.Dimension(759, 709));
        setResizable(false);

        jScrollPane1.setMaximumSize(new java.awt.Dimension(245, 170));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(245, 170));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(245, 170));

        korisniciLst.setFont(new java.awt.Font("Georgia", 2, 14)); // NOI18N
        korisniciLst.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        korisniciLst.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                korisniciLstValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(korisniciLst);

        jLabel1.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        jLabel1.setText("Korisnik:");

        jScrollPane2.setMaximumSize(new java.awt.Dimension(245, 170));
        jScrollPane2.setMinimumSize(new java.awt.Dimension(245, 170));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(245, 170));

        kupLst.setFont(new java.awt.Font("Georgia", 2, 14)); // NOI18N
        kupLst.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(kupLst);

        jScrollPane3.setMaximumSize(new java.awt.Dimension(245, 170));
        jScrollPane3.setMinimumSize(new java.awt.Dimension(245, 170));
        jScrollPane3.setPreferredSize(new java.awt.Dimension(245, 170));

        prodLst.setFont(new java.awt.Font("Georgia", 2, 14)); // NOI18N
        prodLst.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(prodLst);

        kupljena.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        kupljena.setText("Kupljena djela:");

        prodana.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        prodana.setText("Prodana djela:");

        transakcijaTabs.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        transakcijaTabs.setMaximumSize(new java.awt.Dimension(612, 300));
        transakcijaTabs.setMinimumSize(new java.awt.Dimension(612, 300));
        transakcijaTabs.setPreferredSize(new java.awt.Dimension(612, 300));

        pregledLbl.setMaximumSize(new java.awt.Dimension(536, 300));
        pregledLbl.setMinimumSize(new java.awt.Dimension(536, 300));
        pregledLbl.setPreferredSize(new java.awt.Dimension(536, 300));

        djelaLst.setFont(new java.awt.Font("Georgia", 2, 14)); // NOI18N
        djelaLst.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        djelaLst.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                djelaLstValueChanged(evt);
            }
        });
        jScrollPane4.setViewportView(djelaLst);

        nazivK.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        nazivK.setText("Naziv:");

        autorK.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        autorK.setText("Autor:");

        datumK.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        datumK.setText("Datum:");

        nazivKTxt.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        nazivKTxt.setText("Unesite naziv...");
        nazivKTxt.setMaximumSize(new java.awt.Dimension(464, 30));
        nazivKTxt.setMinimumSize(new java.awt.Dimension(464, 30));
        nazivKTxt.setPreferredSize(new java.awt.Dimension(464, 30));

        opisK.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        opisK.setText("Opis:");

        traziKTxt.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        traziKTxt.setText("jTextField1");
        traziKTxt.setMaximumSize(new java.awt.Dimension(80, 30));
        traziKTxt.setMinimumSize(new java.awt.Dimension(80, 30));
        traziKTxt.setPreferredSize(new java.awt.Dimension(80, 30));

        traziKBttn.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        traziKBttn.setText("Traži");
        traziKBttn.setMaximumSize(new java.awt.Dimension(98, 20));
        traziKBttn.setMinimumSize(new java.awt.Dimension(98, 20));
        traziKBttn.setPreferredSize(new java.awt.Dimension(98, 20));
        traziKBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                traziKBttnActionPerformed(evt);
            }
        });

        kupiBttn.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        kupiBttn.setText("Kupi");
        kupiBttn.setMaximumSize(new java.awt.Dimension(98, 20));
        kupiBttn.setMinimumSize(new java.awt.Dimension(98, 20));
        kupiBttn.setPreferredSize(new java.awt.Dimension(98, 20));
        kupiBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kupiBttnActionPerformed(evt);
            }
        });

        povratakKBttn.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        povratakKBttn.setText("Povratak");
        povratakKBttn.setMaximumSize(new java.awt.Dimension(98, 20));
        povratakKBttn.setMinimumSize(new java.awt.Dimension(98, 20));
        povratakKBttn.setPreferredSize(new java.awt.Dimension(98, 20));
        povratakKBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                povratakKBttnActionPerformed(evt);
            }
        });

        cijenaKTxt.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        cijenaKTxt.setText("jTextField1");
        cijenaKTxt.setMaximumSize(new java.awt.Dimension(464, 30));
        cijenaKTxt.setMinimumSize(new java.awt.Dimension(464, 30));
        cijenaKTxt.setPreferredSize(new java.awt.Dimension(464, 30));

        cijenaK.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        cijenaK.setText("Cijena:");

        autorKCmb.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        autorKCmb.setMaximumSize(new java.awt.Dimension(464, 30));
        autorKCmb.setMinimumSize(new java.awt.Dimension(464, 30));
        autorKCmb.setPreferredSize(new java.awt.Dimension(464, 30));

        opisKTxt.setColumns(20);
        opisKTxt.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        opisKTxt.setRows(5);
        jScrollPane5.setViewportView(opisKTxt);

        datumKTxt.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        datumKTxt.setText("jTextField1");
        datumKTxt.setMaximumSize(new java.awt.Dimension(464, 30));
        datumKTxt.setMinimumSize(new java.awt.Dimension(464, 30));
        datumKTxt.setPreferredSize(new java.awt.Dimension(464, 30));

        javax.swing.GroupLayout kupnjaTabLayout = new javax.swing.GroupLayout(kupnjaTab);
        kupnjaTab.setLayout(kupnjaTabLayout);
        kupnjaTabLayout.setHorizontalGroup(
            kupnjaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kupnjaTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kupnjaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(kupnjaTabLayout.createSequentialGroup()
                        .addGroup(kupnjaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nazivK)
                            .addComponent(autorK)
                            .addComponent(datumK)
                            .addComponent(opisK)
                            .addComponent(cijenaK))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(kupnjaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cijenaKTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nazivKTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(autorKCmb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane5)
                            .addComponent(datumKTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(pregledLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(kupnjaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kupnjaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                        .addComponent(traziKTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(kupnjaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(traziKBttn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, kupnjaTabLayout.createSequentialGroup()
                            .addComponent(povratakKBttn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(kupiBttn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        kupnjaTabLayout.setVerticalGroup(
            kupnjaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kupnjaTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kupnjaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kupnjaTabLayout.createSequentialGroup()
                        .addComponent(pregledLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(kupnjaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nazivKTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nazivK))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(kupnjaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(autorKCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(autorK))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(kupnjaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(datumKTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(datumK))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(kupnjaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(opisK)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(kupnjaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cijenaKTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cijenaK)))
                    .addGroup(kupnjaTabLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(traziKTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(traziKBttn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(kupnjaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(povratakKBttn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kupiBttn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        transakcijaTabs.addTab("Kupnja", kupnjaTab);

        nazivP.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        nazivP.setText("Naziv:");

        nazivPTxt.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        nazivPTxt.setText("Unesite naziv...");

        datumPTxt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd.MM.yyyy."))));
        datumPTxt.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N

        autorPCmb.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N

        opisPTxt.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        opisPTxt.setText("Unesite opis...");

        datumP.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        datumP.setText("Datum:");

        autorP.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        autorP.setText("Autor:");

        opisP.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        opisP.setText("Opis:");

        prodajBttn.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        prodajBttn.setText("Prodaj");
        prodajBttn.setMaximumSize(new java.awt.Dimension(77, 45));
        prodajBttn.setMinimumSize(new java.awt.Dimension(77, 45));
        prodajBttn.setPreferredSize(new java.awt.Dimension(77, 45));
        prodajBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodajBttnActionPerformed(evt);
            }
        });

        ocistiBttn.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        ocistiBttn.setText("Očisti");
        ocistiBttn.setMaximumSize(new java.awt.Dimension(77, 45));
        ocistiBttn.setMinimumSize(new java.awt.Dimension(77, 45));
        ocistiBttn.setPreferredSize(new java.awt.Dimension(77, 45));
        ocistiBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ocistiBttnActionPerformed(evt);
            }
        });

        prodajDflt.setMaximumSize(new java.awt.Dimension(640, 277));
        prodajDflt.setMinimumSize(new java.awt.Dimension(640, 277));
        prodajDflt.setPreferredSize(new java.awt.Dimension(640, 277));
        prodajDflt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                prodajDfltMouseClicked(evt);
            }
        });

        povratakPBttn.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        povratakPBttn.setText("Povratak");
        povratakPBttn.setMaximumSize(new java.awt.Dimension(77, 45));
        povratakPBttn.setMinimumSize(new java.awt.Dimension(77, 45));
        povratakPBttn.setPreferredSize(new java.awt.Dimension(77, 45));
        povratakPBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                povratakPBttnActionPerformed(evt);
            }
        });

        porukaLbl.setFont(new java.awt.Font("Georgia", 2, 14)); // NOI18N
        porukaLbl.setText("jLabel3");

        cijenaPTxt.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N

        cijenaP.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        cijenaP.setText("Cijena:");

        javax.swing.GroupLayout prodajaTabLayout = new javax.swing.GroupLayout(prodajaTab);
        prodajaTab.setLayout(prodajaTabLayout);
        prodajaTabLayout.setHorizontalGroup(
            prodajaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(prodajaTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(prodajaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nazivP)
                    .addComponent(datumP)
                    .addComponent(autorP)
                    .addComponent(opisP)
                    .addComponent(cijenaP))
                .addGap(16, 16, 16)
                .addGroup(prodajaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(porukaLbl)
                    .addGroup(prodajaTabLayout.createSequentialGroup()
                        .addGroup(prodajaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cijenaPTxt)
                            .addComponent(datumPTxt, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(autorPCmb, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nazivPTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
                            .addComponent(opisPTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(prodajaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(prodajBttn, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(ocistiBttn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(povratakPBttn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, prodajaTabLayout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(prodajDflt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );
        prodajaTabLayout.setVerticalGroup(
            prodajaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(prodajaTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(prodajaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(prodajaTabLayout.createSequentialGroup()
                        .addComponent(prodajBttn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ocistiBttn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(povratakPBttn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(prodajaTabLayout.createSequentialGroup()
                        .addGroup(prodajaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nazivPTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nazivP))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(prodajaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(datumPTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(datumP))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(prodajaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(autorPCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(autorP))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(prodajaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(opisPTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(opisP))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(prodajaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cijenaPTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cijenaP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(porukaLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prodajDflt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        transakcijaTabs.addTab("Prodaja", prodajaTab);

        xx1.setText("jLabel2");

        a1.setText("jLabel2");

        a2.setText("jLabel2");

        a3.setText("jLabel2");

        a4.setText("jLabel2");

        a5.setText("jLabel2");

        a6.setText("jLabel2");

        a7.setText("jLabel2");

        a8.setText("jLabel2");

        a9.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(transakcijaTabs, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(45, 45, 45)
                                .addComponent(xx1))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kupljena))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(prodana)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(a1)
                    .addComponent(a9)
                    .addComponent(a8)
                    .addComponent(a7)
                    .addComponent(a6)
                    .addComponent(a5)
                    .addComponent(a4)
                    .addComponent(a3)
                    .addComponent(a2))
                .addContainerGap(379, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(kupljena)
                    .addComponent(prodana)
                    .addComponent(xx1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(transakcijaTabs, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(a1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(a2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(a3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(a4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(a5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(a6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(a7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(a8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(a9))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void prodajDfltMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prodajDfltMouseClicked
        JOptionPane.showMessageDialog(this,
                "The Dance Lesson (sometimes known as The Dancing Lesson) is\n"
                + "an oil on canvas painting by the French artist Edgar Degas created\n"
                + "around 1879. It is currently kept at the National Gallery of Art in\n"
                + "Washington, D.C. There is at least one other work by Degas by\n"
                + "this title, also made in about 1879, which is a pastel.");
    }//GEN-LAST:event_prodajDfltMouseClicked

    private void povratakPBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_povratakPBttnActionPerformed
        this.dispose();
    }//GEN-LAST:event_povratakPBttnActionPerformed

    private void povratakKBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_povratakKBttnActionPerformed
        this.dispose();
    }//GEN-LAST:event_povratakKBttnActionPerformed

    private void korisniciLstValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_korisniciLstValueChanged
        /*try {
            DefaultListModel<Djelo> m = new DefaultListModel<>();
            new ObradaKorisnik().getEntitet().getKupDjela().forEach(p -> {
                m.addElement(p);
            });
        } catch (java.lang.NullPointerException ex) {
            porukaLbl.setText("Korisnik nema kupljenih djela!");
        }
        try {
            DefaultListModel<Djelo> n = new DefaultListModel<>();
            new ObradaKorisnik().getEntitet().getProdDjela().forEach(r -> {
                n.addElement(r);
            });
        } catch (java.lang.NullPointerException ex) {
            porukaLbl.setText("Korisnik nema pordanih djela!");
        }*/

    }//GEN-LAST:event_korisniciLstValueChanged

    private void kupiBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kupiBttnActionPerformed
        entitetK = korisniciLst.getSelectedValue();
        if (entitetK == null) {
            return;
        }
        
        postaviVrijednostiUEntitet();

        
        try {
            obradaK.update();
            ucitajKorisnike();
            emptyFields();
        } catch (SkrbinaException e) {
            xx1.setText(e.getPoruka());
        }
    }//GEN-LAST:event_kupiBttnActionPerformed

    private void ocistiBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ocistiBttnActionPerformed
        clearFields();
    }//GEN-LAST:event_ocistiBttnActionPerformed

    private void prodajBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodajBttnActionPerformed
        entitetK = korisniciLst.getSelectedValue();
        entitetD = new Djelo();

        entitetD.setNaziv(nazivPTxt.getText());
        entitetD.setDatum(datumPTxt.getText());
        entitetD.setAutor((Autor) autorPCmb.getSelectedItem());
        entitetD.setOpis(opisPTxt.getText());

        obradaD.setEntitet(entitetD);

        try {
            obradaD.create();
            //ucitajProdano();
            clearFields();
        } catch (SkrbinaException ex) {
            porukaLbl.setText(ex.getPoruka());
        }
    }//GEN-LAST:event_prodajBttnActionPerformed

    private void djelaLstValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_djelaLstValueChanged
        pregledLbl.setIcon(dfltImg);
        pregledLbl.setText("");
        try {
            String slika = djelaLst.getSelectedValue().getNaziv();
            img = new ImageIcon(getClass().getResource("/" + slika + ".jpg"));
            if (img != null) {
                pregledLbl.setIcon(img);
                pregledLbl.setText("");
            } else {
                pregledLbl.setIcon(dfltImg);
                pregledLbl.setText("");

            }
        } catch (Exception x) {
            porukaLbl.setText(x.getMessage());
        }

        if (evt.getValueIsAdjusting()) {
            return;
        }

        entitetD = djelaLst.getSelectedValue();
        if (entitetD == null) {
            return;
        }
        nazivKTxt.setText(entitetD.getNaziv());
        DefaultComboBoxModel<Autor> auth = (DefaultComboBoxModel<Autor>) autorKCmb.getModel();
        for (int i = 0; i < auth.getSize(); i++) {
            if (auth.getElementAt(i).getId().equals(entitetD.getAutor().getId())) {
                autorKCmb.setSelectedIndex(i);
                break;
            }
        }
        datumKTxt.setText(entitetD.getDatum());
        opisKTxt.setText(entitetD.getOpis());
        cijenaKTxt.setText(entitetD.getCijena().toString());
        kupiBttn.setEnabled(true);
    }//GEN-LAST:event_djelaLstValueChanged

    private void traziKBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_traziKBttnActionPerformed
        ucitajZaTrazi();
    }//GEN-LAST:event_traziKBttnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transakcije.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transakcije.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transakcije.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transakcije.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transakcije().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel a1;
    private javax.swing.JLabel a2;
    private javax.swing.JLabel a3;
    private javax.swing.JLabel a4;
    private javax.swing.JLabel a5;
    private javax.swing.JLabel a6;
    private javax.swing.JLabel a7;
    private javax.swing.JLabel a8;
    private javax.swing.JLabel a9;
    private javax.swing.JLabel autorK;
    private javax.swing.JComboBox<Autor> autorKCmb;
    private javax.swing.JLabel autorP;
    private javax.swing.JComboBox<Autor> autorPCmb;
    private javax.swing.JLabel cijenaK;
    private javax.swing.JTextField cijenaKTxt;
    private javax.swing.JLabel cijenaP;
    private javax.swing.JTextField cijenaPTxt;
    private javax.swing.JLabel datumK;
    private javax.swing.JTextField datumKTxt;
    private javax.swing.JLabel datumP;
    private javax.swing.JFormattedTextField datumPTxt;
    private javax.swing.JList<Djelo> djelaLst;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JList<Korisnik> korisniciLst;
    private javax.swing.JList<Djelo> kupLst;
    private javax.swing.JButton kupiBttn;
    private javax.swing.JLabel kupljena;
    private javax.swing.JPanel kupnjaTab;
    private javax.swing.JLabel nazivK;
    private javax.swing.JTextField nazivKTxt;
    private javax.swing.JLabel nazivP;
    private javax.swing.JTextField nazivPTxt;
    private javax.swing.JButton ocistiBttn;
    private javax.swing.JLabel opisK;
    private javax.swing.JTextArea opisKTxt;
    private javax.swing.JLabel opisP;
    private javax.swing.JTextField opisPTxt;
    private javax.swing.JLabel porukaLbl;
    private javax.swing.JButton povratakKBttn;
    private javax.swing.JButton povratakPBttn;
    private javax.swing.JLabel pregledLbl;
    private javax.swing.JList<Djelo> prodLst;
    private javax.swing.JButton prodajBttn;
    private javax.swing.JLabel prodajDflt;
    private javax.swing.JPanel prodajaTab;
    private javax.swing.JLabel prodana;
    private javax.swing.JTabbedPane transakcijaTabs;
    private javax.swing.JButton traziKBttn;
    private javax.swing.JTextField traziKTxt;
    private javax.swing.JLabel xx1;
    // End of variables declaration//GEN-END:variables

    private void clearFields() {
        nazivPTxt.setText("");
        datumPTxt.setText("");
        opisPTxt.setText("");
        porukaLbl.setText("");
    }

    private void setFirstDefault() {
        nazivKTxt.setEditable(false);
        datumKTxt.setEditable(false);
        autorKCmb.setEditable(false);
        opisKTxt.setEditable(false);
        cijenaKTxt.setEditable(false);
        nazivPTxt.setEnabled(false);
        datumPTxt.setEnabled(false);
        opisPTxt.setEnabled(false);
        cijenaPTxt.setEnabled(false);
        kupiBttn.setEnabled(false);
        prodajBttn.setEnabled(false);
        ocistiBttn.setEnabled(false);
    }

    private void emptyFields() {
        nazivKTxt.setText("");
        datumKTxt.setText("");
        opisKTxt.setText("");
        cijenaKTxt.setText("");
        nazivPTxt.setText("");
        datumPTxt.setText("");
        opisPTxt.setText("");
        cijenaPTxt.setText("");
        traziKTxt.setText("");
        porukaLbl.setText("");
    }

    private void ucitajKorisnike() {
        DefaultListModel<Korisnik> m = new DefaultListModel<>();
        obradaK.getPodaci().forEach(r -> m.addElement(r));
        korisniciLst.setModel(m);
    }

    private void ucitajKupnju() {
        opisKTxt.setWrapStyleWord(true);
        opisKTxt.setLineWrap(true);
        obradaD = new ObradaDjelo();
        djelaLst.setCellRenderer(new DjeloCellRenderer());
        DefaultListModel<Djelo> m = new DefaultListModel<>();
        obradaD.getPodaci().forEach(r -> m.addElement(r));
        djelaLst.setModel(m);
        DefaultComboBoxModel<Autor> mp = new DefaultComboBoxModel<>();
        new ObradaAutor().getPodaci().forEach(p -> {
            mp.addElement(p);
        });
        autorKCmb.setRenderer(new OsobaCellRenderer());
        autorKCmb.setModel(mp);
    }

    private void ucitajZaTrazi() {
        DefaultListModel<Djelo> m = new DefaultListModel<>();
        obradaD.getPodaci(traziKTxt.getText()).forEach(k -> m.addElement(k));
        djelaLst.setModel(m);
    }

    private void postaviUEntKupnja() {
        entitetD.setNaziv(djelaLst.getSelectedValue().getNaziv());
        entitetD.setAutor(djelaLst.getSelectedValue().getAutor());
        entitetD.setDatum(djelaLst.getSelectedValue().getDatum());
        entitetD.setOpis(djelaLst.getSelectedValue().getOpis());
        entitetD.setCijena(djelaLst.getSelectedValue().getCijena());
        obradaD.setEntitet(entitetD);
    }

    private void postaviVrijednostiUEntitet() {
        entitetK.setIme(entitetK.getIme());
        entitetK.setPrezime(entitetK.getPrezime());
        entitetK.setRodjendan(entitetK.getRodjendan());
        entitetK.setOib(entitetK.getOib());
        entitetK.setMjesto_Rodjenja(entitetK.getMjesto_Rodjenja());
        entitetK.setIBAN(entitetK.getIBAN());
        entitetK.setKontakt(entitetK.getKontakt());
        entitetK.setUlogaGalerija("korisnik");
        obradaK.setEntitet(entitetK);
    }
}
