/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hr.skrbina.edunovazavrsnigalerija.view;

import javax.swing.ImageIcon;

/**
 *
 * @author Hrvoje
 */
public class Transakcije extends javax.swing.JFrame {
ImageIcon dflt = new ImageIcon(getClass().getResource("/osoba_def.jpg"));
    /**
     * Creates new form Transakcije
     */
    public Transakcije() {
        initComponents();
        slikaLabel.setIcon(dflt);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        transakcije = new javax.swing.JTabbedPane();
        kupnja = new javax.swing.JPanel();
        prodaja = new javax.swing.JPanel();
        kupljenoLista = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        korisnikLabel = new javax.swing.JLabel();
        korisnikLista = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        oKorisnikBttn = new javax.swing.JButton();
        prodanoLista = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList<>();
        kupljenoLabel = new javax.swing.JLabel();
        prodanoLabel = new javax.swing.JLabel();
        slikaLabel = new javax.swing.JLabel();
        oDjelaBttn = new javax.swing.JButton();
        izlz = new javax.swing.JButton();
        pvrtk1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout kupnjaLayout = new javax.swing.GroupLayout(kupnja);
        kupnja.setLayout(kupnjaLayout);
        kupnjaLayout.setHorizontalGroup(
            kupnjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 534, Short.MAX_VALUE)
        );
        kupnjaLayout.setVerticalGroup(
            kupnjaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 412, Short.MAX_VALUE)
        );

        transakcije.addTab("Kupnja", kupnja);

        javax.swing.GroupLayout prodajaLayout = new javax.swing.GroupLayout(prodaja);
        prodaja.setLayout(prodajaLayout);
        prodajaLayout.setHorizontalGroup(
            prodajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 534, Short.MAX_VALUE)
        );
        prodajaLayout.setVerticalGroup(
            prodajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 412, Short.MAX_VALUE)
        );

        transakcije.addTab("Prodaja", prodaja);

        jList1.setFont(new java.awt.Font("Georgia", 2, 14)); // NOI18N
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        kupljenoLista.setViewportView(jList1);

        korisnikLabel.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        korisnikLabel.setText("Korisnik:");

        jList2.setFont(new java.awt.Font("Georgia", 2, 14)); // NOI18N
        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        korisnikLista.setViewportView(jList2);

        oKorisnikBttn.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        oKorisnikBttn.setText("Otvori korisnike");
        oKorisnikBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oKorisnikBttnActionPerformed(evt);
            }
        });

        jList3.setFont(new java.awt.Font("Georgia", 2, 14)); // NOI18N
        jList3.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        prodanoLista.setViewportView(jList3);

        kupljenoLabel.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        kupljenoLabel.setText("Kupljena djela:");

        prodanoLabel.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        prodanoLabel.setText("Prodana djela:");

        oDjelaBttn.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        oDjelaBttn.setText("Otvori djela");
        oDjelaBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oDjelaBttnActionPerformed(evt);
            }
        });

        izlz.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        izlz.setText("Izlaz");
        izlz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                izlzActionPerformed(evt);
            }
        });

        pvrtk1.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        pvrtk1.setText("Povratak");
        pvrtk1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pvrtk1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(kupljenoLista)
                            .addComponent(kupljenoLabel)
                            .addComponent(korisnikLabel)
                            .addComponent(korisnikLista)
                            .addComponent(oKorisnikBttn, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)))
                    .addComponent(pvrtk1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(prodanoLabel)
                            .addComponent(prodanoLista, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(slikaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(oDjelaBttn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(izlz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(transakcije, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kupljenoLabel)
                    .addComponent(prodanoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(prodanoLista, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(kupljenoLista, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(korisnikLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(slikaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(korisnikLista, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oDjelaBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(oKorisnikBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(izlz, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pvrtk1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(transakcije, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void oKorisnikBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oKorisnikBttnActionPerformed
        Korisnici kor = new Korisnici();
        kor.setLocationRelativeTo(null);
        kor.setVisible(true);
    }//GEN-LAST:event_oKorisnikBttnActionPerformed

    private void oDjelaBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oDjelaBttnActionPerformed
        Djela djl = new Djela();
        djl.setLocationRelativeTo(null);
        djl.setVisible(true);
    }//GEN-LAST:event_oDjelaBttnActionPerformed

    private void izlzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_izlzActionPerformed
        System.exit(0);
    }//GEN-LAST:event_izlzActionPerformed

    private void pvrtk1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pvrtk1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_pvrtk1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transakcije.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transakcije.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transakcije.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transakcije.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transakcije().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton izlz;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JList<String> jList3;
    private javax.swing.JLabel korisnikLabel;
    private javax.swing.JScrollPane korisnikLista;
    private javax.swing.JLabel kupljenoLabel;
    private javax.swing.JScrollPane kupljenoLista;
    private javax.swing.JPanel kupnja;
    private javax.swing.JButton oDjelaBttn;
    private javax.swing.JButton oKorisnikBttn;
    private javax.swing.JPanel prodaja;
    private javax.swing.JLabel prodanoLabel;
    private javax.swing.JScrollPane prodanoLista;
    private javax.swing.JButton pvrtk1;
    private javax.swing.JLabel slikaLabel;
    private javax.swing.JTabbedPane transakcije;
    // End of variables declaration//GEN-END:variables
}
