/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hr.skrbina.edunovazavrsnigalerija.view;

import hr.skrbina.edunovazavrsnigalerija.controller.ObradaDjelo;
import hr.skrbina.edunovazavrsnigalerija.controller.ObradaKorisnik;
import hr.skrbina.edunovazavrsnigalerija.model.Autor;
import hr.skrbina.edunovazavrsnigalerija.model.Djelo;
import hr.skrbina.edunovazavrsnigalerija.model.Korisnik;
import hr.skrbina.edunovazavrsnigalerija.utility.SkrbinaException;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Hrvoje
 */
public class Transakcije extends javax.swing.JFrame {

    private final ObradaKorisnik obradaK;
    private Korisnik entitetK;
    private ObradaDjelo obradaD;
    private Djelo entitetD;

    /**
     * Creates new form Transakcije
     */
    public Transakcije() {
        initComponents();
        setTitle("Gallery Exclusive - Transakcije");
        obradaK = new ObradaKorisnik();
        if (korisniciLst.isSelectionEmpty()) {
            setFirstDefault();
        }
        emptyFields();
        ucitajKorisnike();

        noEdit();
        prodajDflt.setIcon(new ImageIcon(getClass().getResource("/degasDflt.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        korisniciLst = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        kupLst = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        prodLst = new javax.swing.JList<>();
        kupljena = new javax.swing.JLabel();
        prodana = new javax.swing.JLabel();
        transakcijaTabs = new javax.swing.JTabbedPane();
        kupnjaTab = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        djelaLst = new javax.swing.JList<>();
        nazivK = new javax.swing.JLabel();
        autorK = new javax.swing.JLabel();
        datumK = new javax.swing.JLabel();
        datumKTxt = new javax.swing.JFormattedTextField();
        nazivKTxt = new javax.swing.JTextField();
        opisKTxt = new javax.swing.JTextField();
        opisK = new javax.swing.JLabel();
        traziKTxt = new javax.swing.JTextField();
        traziKBttn = new javax.swing.JButton();
        kupiBttn = new javax.swing.JButton();
        povratakKBttn = new javax.swing.JButton();
        autorKTxt = new javax.swing.JTextField();
        cijenaKTxt = new javax.swing.JTextField();
        cijenaK = new javax.swing.JLabel();
        prodajaTab = new javax.swing.JPanel();
        nazivP = new javax.swing.JLabel();
        nazivPTxt = new javax.swing.JTextField();
        datumPTxt = new javax.swing.JFormattedTextField();
        autorPCmb = new javax.swing.JComboBox<>();
        opisPTxt = new javax.swing.JTextField();
        datumP = new javax.swing.JLabel();
        autorP = new javax.swing.JLabel();
        opisP = new javax.swing.JLabel();
        prodajBttn = new javax.swing.JButton();
        ocistiBttn = new javax.swing.JButton();
        prodajDflt = new javax.swing.JLabel();
        povratakPBttn = new javax.swing.JButton();
        porukaLbl = new javax.swing.JLabel();
        cijenaPTxt = new javax.swing.JTextField();
        cijenaP = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(759, 709));
        setMinimumSize(new java.awt.Dimension(759, 709));
        setResizable(false);

        jScrollPane1.setMaximumSize(new java.awt.Dimension(245, 170));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(245, 170));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(245, 170));

        korisniciLst.setFont(new java.awt.Font("Georgia", 2, 14)); // NOI18N
        korisniciLst.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        korisniciLst.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                korisniciLstValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(korisniciLst);

        jLabel1.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        jLabel1.setText("Korisnik:");

        jScrollPane2.setMaximumSize(new java.awt.Dimension(245, 170));
        jScrollPane2.setMinimumSize(new java.awt.Dimension(245, 170));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(245, 170));

        kupLst.setFont(new java.awt.Font("Georgia", 2, 14)); // NOI18N
        kupLst.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(kupLst);

        jScrollPane3.setMaximumSize(new java.awt.Dimension(245, 170));
        jScrollPane3.setMinimumSize(new java.awt.Dimension(245, 170));
        jScrollPane3.setPreferredSize(new java.awt.Dimension(245, 170));

        prodLst.setFont(new java.awt.Font("Georgia", 2, 14)); // NOI18N
        prodLst.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(prodLst);

        kupljena.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        kupljena.setText("Kupljena djela:");

        prodana.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        prodana.setText("Prodana djela:");

        transakcijaTabs.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        transakcijaTabs.setMaximumSize(new java.awt.Dimension(612, 300));
        transakcijaTabs.setMinimumSize(new java.awt.Dimension(612, 300));
        transakcijaTabs.setPreferredSize(new java.awt.Dimension(612, 300));

        jLabel2.setMaximumSize(new java.awt.Dimension(536, 300));
        jLabel2.setMinimumSize(new java.awt.Dimension(536, 300));
        jLabel2.setPreferredSize(new java.awt.Dimension(536, 300));

        djelaLst.setFont(new java.awt.Font("Georgia", 2, 14)); // NOI18N
        djelaLst.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane4.setViewportView(djelaLst);

        nazivK.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        nazivK.setText("Naziv:");

        autorK.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        autorK.setText("Autor:");

        datumK.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        datumK.setText("Datum:");

        datumKTxt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd.MM.yyyy."))));
        datumKTxt.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N

        nazivKTxt.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        nazivKTxt.setText("Unesite naziv...");

        opisKTxt.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        opisKTxt.setText("Unesite opis...");

        opisK.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        opisK.setText("Opis:");

        traziKTxt.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        traziKTxt.setText("jTextField1");

        traziKBttn.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        traziKBttn.setText("Traži");
        traziKBttn.setMaximumSize(new java.awt.Dimension(98, 20));
        traziKBttn.setMinimumSize(new java.awt.Dimension(98, 20));
        traziKBttn.setPreferredSize(new java.awt.Dimension(98, 20));

        kupiBttn.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        kupiBttn.setText("Kupi");
        kupiBttn.setMaximumSize(new java.awt.Dimension(98, 20));
        kupiBttn.setMinimumSize(new java.awt.Dimension(98, 20));
        kupiBttn.setPreferredSize(new java.awt.Dimension(98, 20));
        kupiBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kupiBttnActionPerformed(evt);
            }
        });

        povratakKBttn.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        povratakKBttn.setText("Povratak");
        povratakKBttn.setMaximumSize(new java.awt.Dimension(98, 20));
        povratakKBttn.setMinimumSize(new java.awt.Dimension(98, 20));
        povratakKBttn.setPreferredSize(new java.awt.Dimension(98, 20));
        povratakKBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                povratakKBttnActionPerformed(evt);
            }
        });

        autorKTxt.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        autorKTxt.setText("jTextField1");

        cijenaKTxt.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        cijenaKTxt.setText("jTextField1");

        cijenaK.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        cijenaK.setText("Cijena:");

        javax.swing.GroupLayout kupnjaTabLayout = new javax.swing.GroupLayout(kupnjaTab);
        kupnjaTab.setLayout(kupnjaTabLayout);
        kupnjaTabLayout.setHorizontalGroup(
            kupnjaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kupnjaTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kupnjaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kupnjaTabLayout.createSequentialGroup()
                        .addGroup(kupnjaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(autorK)
                            .addComponent(nazivK)
                            .addComponent(datumK)
                            .addComponent(opisK)
                            .addComponent(cijenaK))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(kupnjaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cijenaKTxt)
                            .addComponent(datumKTxt, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nazivKTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
                            .addComponent(opisKTxt)
                            .addComponent(autorKTxt))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(kupnjaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(traziKTxt, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(traziKBttn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, kupnjaTabLayout.createSequentialGroup()
                        .addComponent(povratakKBttn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kupiBttn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(578, 578, 578))
        );
        kupnjaTabLayout.setVerticalGroup(
            kupnjaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kupnjaTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kupnjaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(kupnjaTabLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(kupnjaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kupnjaTabLayout.createSequentialGroup()
                                .addComponent(nazivKTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(kupnjaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(datumKTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(datumK))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(kupnjaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(autorK)
                                    .addComponent(autorKTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(nazivK))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(kupnjaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(opisK)
                            .addComponent(opisKTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(kupnjaTabLayout.createSequentialGroup()
                        .addComponent(jScrollPane4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(traziKTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(traziKBttn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(kupnjaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cijenaKTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cijenaK)
                    .addComponent(povratakKBttn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kupiBttn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        transakcijaTabs.addTab("Kupnja", kupnjaTab);

        nazivP.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        nazivP.setText("Naziv:");

        nazivPTxt.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        nazivPTxt.setText("Unesite naziv...");

        datumPTxt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd.MM.yyyy."))));
        datumPTxt.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N

        autorPCmb.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N

        opisPTxt.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        opisPTxt.setText("Unesite opis...");

        datumP.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        datumP.setText("Datum:");

        autorP.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        autorP.setText("Autor:");

        opisP.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        opisP.setText("Opis:");

        prodajBttn.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        prodajBttn.setText("Prodaj");
        prodajBttn.setMaximumSize(new java.awt.Dimension(77, 45));
        prodajBttn.setMinimumSize(new java.awt.Dimension(77, 45));
        prodajBttn.setPreferredSize(new java.awt.Dimension(77, 45));
        prodajBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodajBttnActionPerformed(evt);
            }
        });

        ocistiBttn.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        ocistiBttn.setText("Očisti");
        ocistiBttn.setMaximumSize(new java.awt.Dimension(77, 45));
        ocistiBttn.setMinimumSize(new java.awt.Dimension(77, 45));
        ocistiBttn.setPreferredSize(new java.awt.Dimension(77, 45));
        ocistiBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ocistiBttnActionPerformed(evt);
            }
        });

        prodajDflt.setMaximumSize(new java.awt.Dimension(640, 277));
        prodajDflt.setMinimumSize(new java.awt.Dimension(640, 277));
        prodajDflt.setPreferredSize(new java.awt.Dimension(640, 277));
        prodajDflt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                prodajDfltMouseClicked(evt);
            }
        });

        povratakPBttn.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        povratakPBttn.setText("Povratak");
        povratakPBttn.setMaximumSize(new java.awt.Dimension(77, 45));
        povratakPBttn.setMinimumSize(new java.awt.Dimension(77, 45));
        povratakPBttn.setPreferredSize(new java.awt.Dimension(77, 45));
        povratakPBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                povratakPBttnActionPerformed(evt);
            }
        });

        porukaLbl.setFont(new java.awt.Font("Georgia", 2, 14)); // NOI18N
        porukaLbl.setText("jLabel3");

        cijenaPTxt.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N

        cijenaP.setFont(new java.awt.Font("Georgia", 3, 14)); // NOI18N
        cijenaP.setText("Cijena:");

        javax.swing.GroupLayout prodajaTabLayout = new javax.swing.GroupLayout(prodajaTab);
        prodajaTab.setLayout(prodajaTabLayout);
        prodajaTabLayout.setHorizontalGroup(
            prodajaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(prodajaTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(prodajaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nazivP)
                    .addComponent(datumP)
                    .addComponent(autorP)
                    .addComponent(opisP)
                    .addComponent(cijenaP))
                .addGap(16, 16, 16)
                .addGroup(prodajaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(porukaLbl)
                    .addGroup(prodajaTabLayout.createSequentialGroup()
                        .addGroup(prodajaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cijenaPTxt)
                            .addComponent(datumPTxt, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(autorPCmb, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nazivPTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
                            .addComponent(opisPTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(prodajaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(prodajBttn, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(ocistiBttn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(povratakPBttn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, prodajaTabLayout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(prodajDflt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );
        prodajaTabLayout.setVerticalGroup(
            prodajaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(prodajaTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(prodajaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(prodajaTabLayout.createSequentialGroup()
                        .addComponent(prodajBttn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ocistiBttn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(povratakPBttn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(prodajaTabLayout.createSequentialGroup()
                        .addGroup(prodajaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nazivPTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nazivP))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(prodajaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(datumPTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(datumP))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(prodajaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(autorPCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(autorP))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(prodajaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(opisPTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(opisP))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(prodajaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cijenaPTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cijenaP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(porukaLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prodajDflt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        transakcijaTabs.addTab("Prodaja", prodajaTab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kupljena))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(prodana)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(transakcijaTabs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(kupljena)
                    .addComponent(prodana))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(transakcijaTabs, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void prodajDfltMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prodajDfltMouseClicked
        JOptionPane.showMessageDialog(this,
                "The Dance Lesson (sometimes known as The Dancing Lesson) is\n"
                + "an oil on canvas painting by the French artist Edgar Degas created\n"
                + "around 1879. It is currently kept at the National Gallery of Art in\n"
                + "Washington, D.C. There is at least one other work by Degas by\n"
                + "this title, also made in about 1879, which is a pastel.");
    }//GEN-LAST:event_prodajDfltMouseClicked

    private void povratakPBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_povratakPBttnActionPerformed
        this.dispose();
    }//GEN-LAST:event_povratakPBttnActionPerformed

    private void povratakKBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_povratakKBttnActionPerformed
        this.dispose();
    }//GEN-LAST:event_povratakKBttnActionPerformed

    private void korisniciLstValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_korisniciLstValueChanged
        DefaultListModel<String> m = new DefaultListModel<>();
        obradaK.getPodaci(entitetK.getKup_Djelo()).forEach(y -> m.addElement(entitetK.getKup_Djelo()));
        kupLst.setModel(m);

        DefaultListModel<String> n = new DefaultListModel<>();
        obradaK.getPodaci(entitetK.getProd_Djelo()).forEach(x -> n.addElement(entitetK.getProd_Djelo()));
        prodLst.setModel(n);

        DefaultListModel<Djelo> d = new DefaultListModel<>();
        obradaD.getPodaci().forEach(z -> d.addElement(z));
        djelaLst.setModel(d);
    }//GEN-LAST:event_korisniciLstValueChanged

    private void kupiBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kupiBttnActionPerformed
        entitetK = korisniciLst.getSelectedValue();
        entitetK.setKup_Djelo(djelaLst.getSelectedValue().getNaziv());
        
        obradaD.setEntitet(entitetD);

        try {
            obradaD.create();
            ucitajKupljeno();
            clearFields();
        } catch (SkrbinaException ex) {
            porukaLbl.setText(ex.getPoruka());
        }
    }//GEN-LAST:event_kupiBttnActionPerformed

    private void ocistiBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ocistiBttnActionPerformed
        clearFields();
    }//GEN-LAST:event_ocistiBttnActionPerformed

    private void prodajBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodajBttnActionPerformed
        entitetK = korisniciLst.getSelectedValue();
        entitetD = new Djelo();

        entitetD.setNaziv(nazivPTxt.getText());
        entitetD.setDatum(datumPTxt.getText());
        entitetD.setAutor((Autor) autorPCmb.getSelectedItem());
        entitetD.setOpis(opisPTxt.getText());

        obradaD.setEntitet(entitetD);

        try {
            obradaD.create();
            ucitajProdano();
            clearFields();
        } catch (SkrbinaException ex) {
            porukaLbl.setText(ex.getPoruka());
        }
    }//GEN-LAST:event_prodajBttnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transakcije.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transakcije.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transakcije.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transakcije.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transakcije().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel autorK;
    private javax.swing.JTextField autorKTxt;
    private javax.swing.JLabel autorP;
    private javax.swing.JComboBox<Autor> autorPCmb;
    private javax.swing.JLabel cijenaK;
    private javax.swing.JTextField cijenaKTxt;
    private javax.swing.JLabel cijenaP;
    private javax.swing.JTextField cijenaPTxt;
    private javax.swing.JLabel datumK;
    private javax.swing.JFormattedTextField datumKTxt;
    private javax.swing.JLabel datumP;
    private javax.swing.JFormattedTextField datumPTxt;
    private javax.swing.JList<Djelo> djelaLst;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JList<Korisnik> korisniciLst;
    private javax.swing.JList<String> kupLst;
    private javax.swing.JButton kupiBttn;
    private javax.swing.JLabel kupljena;
    private javax.swing.JPanel kupnjaTab;
    private javax.swing.JLabel nazivK;
    private javax.swing.JTextField nazivKTxt;
    private javax.swing.JLabel nazivP;
    private javax.swing.JTextField nazivPTxt;
    private javax.swing.JButton ocistiBttn;
    private javax.swing.JLabel opisK;
    private javax.swing.JTextField opisKTxt;
    private javax.swing.JLabel opisP;
    private javax.swing.JTextField opisPTxt;
    private javax.swing.JLabel porukaLbl;
    private javax.swing.JButton povratakKBttn;
    private javax.swing.JButton povratakPBttn;
    private javax.swing.JList<String> prodLst;
    private javax.swing.JButton prodajBttn;
    private javax.swing.JLabel prodajDflt;
    private javax.swing.JPanel prodajaTab;
    private javax.swing.JLabel prodana;
    private javax.swing.JTabbedPane transakcijaTabs;
    private javax.swing.JButton traziKBttn;
    private javax.swing.JTextField traziKTxt;
    // End of variables declaration//GEN-END:variables

    private void clearFields() {
        nazivPTxt.setText("");
        datumPTxt.setText("");
        autorPCmb.setSelectedIndex(-1);
        opisPTxt.setText("");
        porukaLbl.setText("");
    }

    private void setFirstDefault() {
        nazivKTxt.setEnabled(false);
        datumKTxt.setEnabled(false);
        autorKTxt.setEnabled(false);
        opisKTxt.setEnabled(false);
        cijenaKTxt.setEnabled(false);
        nazivPTxt.setEnabled(false);
        datumPTxt.setEnabled(false);
        autorPCmb.setEnabled(false);
        opisPTxt.setEnabled(false);
        cijenaPTxt.setEnabled(false);
        djelaLst.setEnabled(false);
        traziKTxt.setEnabled(false);
        traziKBttn.setEnabled(false);
        kupiBttn.setEnabled(false);
        prodajBttn.setEnabled(false);
        ocistiBttn.setEnabled(false);
    }

    private void noEdit() {
        nazivKTxt.setEditable(false);
        datumKTxt.setEditable(false);
        autorKTxt.setEditable(false);
        opisKTxt.setEditable(false);
        cijenaKTxt.setEditable(false);
    }

    private void emptyFields() {
        nazivKTxt.setText("");
        datumKTxt.setText("");
        autorKTxt.setText("");
        opisKTxt.setText("");
        cijenaKTxt.setText("");
        nazivPTxt.setText("");
        datumPTxt.setText("");
        autorPCmb.setSelectedIndex(-1);
        opisPTxt.setText("");
        cijenaPTxt.setText("");
        traziKTxt.setText("");
        porukaLbl.setText("");
    }

    private void ucitajKorisnike() {
        DefaultListModel<Korisnik> m = new DefaultListModel<>();
        obradaK.getPodaci().forEach(r -> m.addElement(r));
        korisniciLst.setModel(m);
    }

    private void ucitajKupljeno() {
        DefaultListModel<String> m = new DefaultListModel<>();
        m.addElement(obradaK.getEntitet().getKup_Djelo());
        kupLst.setModel(m); // ???
    }

    private void ucitajProdano() {
        DefaultListModel<String> m = new DefaultListModel<>();
        m.addElement(obradaK.getEntitet().getProd_Djelo());
        prodLst.setModel(m); // ???
    }
}
